### ISSUE TITLE
FR19 site specific visualisation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#104]
If a user clicks on a site (a specific feature) then detailed information about that site should be presented 

>The LBIMS shall allow users to view detailed site-specific data on the UI, the data may be in the form of tabular, graphical or statistical displays. The manner in which it will be displayed will be decided during development

Exactly what need to be dsplayed about which sites and how exactly it should be displayed must be specified by LEDET in the form of a template or example before implementation.

child of https://github.com/kartoza/LEDET_BIMS/issues/183

**Comment by gubuntu** [comment]
In the present implementation, this is what will appear in the popup and in the right sidebar when clicking on a biodiversity observation @cchristelis ?

**Comment by meomancer** [comment]
hi @gubuntu 
is it already implemented? with site detail on side panel?

**Comment by Vries14** [comment]
When user clicks on site info on sites are being shown in the right side panel.
