### ISSUE TITLE
Update map control panel view

### ISSUE THREAD

**Issue by dimasciput** [kartoza/LEDET_BIMS#118]
Current view : 

![screen shot 2018-06-21 at 4 21 05 pm](https://user-images.githubusercontent.com/1979569/41710128-1d5631fa-756f-11e8-9e17-62afbbac99a4.png)

New design : 

![screen shot 2018-06-21 at 4 21 32 pm](https://user-images.githubusercontent.com/1979569/41710169-31bb1f52-756f-11e8-8e41-38142fc406bc.png)

see moqups for detailed view

**Comment by gubuntu** [comment]
obsolete
