### ISSUE TITLE
upload page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#128]
- [x] On main upload page I suggest changing 'base collections' to 'Generic observations'
- [x] on specific upload pages I suggest this text (adapt for each module)
'This is the page for uploading fish observation records'

'Upload file here' (not csv)

'These formats are supported: csv' (and we add Excel, ods, shp etc as they get implemented)

'Your data must conform to this schema to be accepted' (show a list of fields and types)

'Duplicates will be detected and rejected' (is this true?)

Once your upload is successful, you will be able to edit it while it awaits validation. Once it is validated, you will no longer be able to edit it'

child of #5

**Comment by dimasciput** [comment]
```
On main upload page I suggest changing 'base collections' to 'Generic observations'
```
Updated in https://github.com/kartoza/LEDET_BIMS/pull/145

**Comment by dimasciput** [comment]
```
Once your upload is successful, you will be able to edit it while it awaits validation. Once it is validated, you will no longer be able to edit it'
```
We need to create separate ticket for this, because it's pretty big feature. And we also need the mockup.

**Comment by gubuntu** [comment]
LGTM
