### ISSUE TITLE
contributions

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#133]
nothing under contributions for kartoza_admin even though that user uploaded some reptile data (maybe this hasn't been implemented yet)

**Comment by dimasciput** [comment]
Yes this hasn't been implemented yet, we don't have any design to work with.

**Comment by dimasciput** [comment]
We can remove this button for now, I guess.

**Comment by gubuntu** [comment]
@carina1000 please flesh out a contributions page mockup or point Dimas to one if there is

**Comment by carina1000** [comment]
Please see contributions mockups here: https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/ab723af6b & https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a6be764a7 

Please add info if I've missed some things

**Comment by ann26** [comment]
hi @carina1000 and @gubuntu 
for this page: https://app.moqups.com/tim@kartoza.com/47tU30vEA3/view/page/a6be764a7
![screenshot from 2018-07-10 15-02-09](https://user-images.githubusercontent.com/26101337/42497095-4cea3c26-8452-11e8-9fa4-542424559ba4.png)

Is this going to be the details page for a single user contributor or a single contribution action?

**Comment by carina1000** [comment]
A single contribution action

**Comment by ann26** [comment]
@carina1000 oh okay, I'm a bit confused here. So the page that list contributions is listing each contributions (like upload history?) ? And if we click on each of it, we'll go to the page for single contribution action?

**Comment by carina1000** [comment]
Exactly @ann26 - but please let me know if you have better ideas?

**Comment by ann26** [comment]
@carina1000 I'm not sure if this is a better idea, so when first I did https://github.com/kartoza/django-bims/pull/121 I thought we are going to show list of the contributors (and their associate objects). We can also show their last activity with the site.
with upload history we will need upload date, it is not available now

**Comment by carina1000** [comment]
Ah yes the "collectors/contributors" page - to be honest I thought this ticket was to show the individual user their upload history/contributions. I will mock the collectors page up soon! Or maybe we should have a quick call to clarify?? @ann26

**Comment by cchristelis** [comment]
@gubuntu, @ann26 and @carina1000 I think we should only have the summary page. The view on map should show the data on the map. The "Add Contribution" button should go.

**Comment by gubuntu** [comment]
This is not a functional requirement for LEDET, it is a core feature from kbims (via healthyrivers). So @cchristelis pls specify. 

From my perspective it's useful to see a summary view of all contributions as well as a report in your own profile showing your contributions. 

Contributions are data sets or documents that a user has uploaded. 

Clicking on a contribution should take the user to that object in its standard page. 
 - if it is a document, go to the document in the document / bibliography section
 - if it is a set of biodiversity records, go the map view with that set as a selected search result..

**Comment by gubuntu** [comment]
This issue was moved to kartoza/healthyrivers#136
