### ISSUE TITLE
documents and reports

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#134]
dead links like this (and contributions) should at least go to a page that says 'under development' or that contains some mock content.

**Comment by dimasciput** [comment]
Either we remove the button, or redirect to 'under development' page, what do you think? @gubuntu

**Comment by gubuntu** [comment]
If it was a production site I would remove the link but at this stage it's probably better for the client to see the structure, so redirect to 'under development'

**Comment by dimasciput** [comment]
@ann26 can you handle this?
