### ISSUE TITLE
biobliography page shows user's activity log

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#135]
when I first went to the bibliography page, there was a stream of what looked like django easy audit logs in the top section of the page. 

They have disappeared subsequently...

**Comment by dimasciput** [comment]
@gubuntu can you elaborate more about thiss issue? I don't quite understand with the title.

**Comment by dimasciput** [comment]
I couldn't replicate this issue, @gubuntu can you test this again?

**Comment by gubuntu** [comment]
I can't right now. Testing is not showing the error and staging only has a map page, no other components???

**Comment by gubuntu** [comment]
The OP does describe what I saw several times, but it's not doing it right now in staging nor testing
