### ISSUE TITLE
map UI

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#136]
- [x] spacing and sizing of the icons on the left needs tweaking - please make spacing and width consistent
- [x] if one selector is opened, others must close. I opened the layer selector and then the base map selector and they overlapped. 
- [x] change 'layers selector' to 'layer selector'

**Comment by dimasciput** [comment]
@gubuntu Most of these issues need to be defined first in a mockup rather we do trial and error. 

@carina1000 can you create a mockup for this? Thanks.

**Comment by gubuntu** [comment]
please proceed with those that don't need a mockup - only the first and third ones probably need Carina's input.

**Comment by carina1000** [comment]
@gubuntu could you please help me with the copy to help explain the LBIMS to new visitors. I have started here: https://docs.google.com/document/d/1VglbMPJz0Ys7gRGkjZgJP4Nb0wpraHkg9Cuq9rK-EQQ/edit

**Comment by gubuntu** [comment]
@carina1000 OK I've made a stab at the text.

**Comment by carina1000** [comment]
@dimasciput check the pop-up mockup https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a85920f2a - we will add more pop ups as we go along for the rest of the tools. The text should be editable from the Django admin page.

**Comment by gubuntu** [comment]
update items in OP

default zoom to Limpopo province needs to be closer (province to fill screen)

**Comment by gubuntu** [comment]
@ann26 I unticked the two items I don't see. And issue fixes need to be merged, deployed in testing and tested before closing

**Comment by gubuntu** [comment]
outstanding items moved to their own issues
