### ISSUE TITLE
filtering issues

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#139]
- does filtering only work on search results? I would expect it to work on records as specified in https://github.com/kartoza/LEDET_BIMS/issues/30
- I would expect start and end dates to be bounded by those in the records being filtered so you start with a valid period covering all records
- I clicked on some names under Collector and nothing happened
- clicking on filter arrows does nothing, only clicking on the filter name collapses or expands the filter. Most people would click on the arrow
- click on a category doesn't do anything

**Comment by dimasciput** [comment]
@gubuntu 
```
- does filtering only work on search results? I would expect it to work on records as specified in #30
```
@meomancer can you address this?

```
- I would expect start and end dates to be bounded by those in the records being filtered so you start with a valid period covering all records
- I clicked on some names under Collector and nothing happened
- click on a category doesn't do anything
```
You need to select the filter first and then click the arrow or click enter in keyboard again.


```
- clicking on filter arrows does nothing, only clicking on the filter name collapses or expands the filter. Most people would click on the arrow
```
It does works on the staging and testing site.

**Comment by gubuntu** [comment]
no these issues still apply (in Firefox 52 on a Mac)

**Comment by dimasciput** [comment]
@gubuntu weird, I tested on the firefox and it was working fine. I use testing server

![bims](https://user-images.githubusercontent.com/1979569/42309738-a7626838-8063-11e8-85bc-672f1ba93fbf.gif)

**Comment by gubuntu** [comment]
the arrow problem is with filter arrows not the search arrow

**Comment by cchristelis** [comment]
This is followed up by issue #137
