### ISSUE TITLE
FR43 implement Google Analytics

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#14]
- get a GA code from a LEDET official (ideally not from Kartoza's Google account) and apply it to the site. 
- document how regular reports can be sent to admin users.

**Comment by Vince-Egan** [comment]
@gubuntu: I'm just waiting for confirmation that https://bims.ledet.gov.za (sub-domain of LEDET's existing web-site) will be suitable as the URL - I'll register the code as soon as that is finalised.

**Comment by Vince-Egan** [comment]
@gubuntu : Here is the Google Analytics code snippet for bims.ledet.gov.za:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122588904-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122588904-1');
</script>

**Comment by dimasciput** [comment]
@Vince-Egan this has been added to the testing server, will need another key for the staging.

**Comment by gubuntu** [comment]
I think it only needs to be added to the production server

**Comment by Vries14** [comment]
google analytics implemented on production
