### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#140]
child of #31

**Comment by dimasciput** [comment]
I guess this fixed by https://github.com/kartoza/django-bims/pull/113

**Comment by dimasciput** [comment]
@gubuntu can you be more specific for this issue?

**Comment by gubuntu** [comment]
several seraches I tried on staging during the demo either did nothing or returned unexpected / wrong results. I'll close this and see how search has improved on testing.
