### ISSUE TITLE
bird data to upload

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#141]
try to get this uploaded as csv or excel or ods in a bird module or a base collection

Take note:
> Here is an example of bird data - this is bird-ringing data. The biometric data belongs to the ringer/SAFRING, so should not be included. The data has been recorded in degrees, minutes and decimal seconds.

[Copy of K Nelson 1540 - Limpopo Bird Ringing Data 2017 - 18.xlsx](https://github.com/kartoza/LEDET_BIMS/files/2164406/Copy.of.K.Nelson.1540.-.Limpopo.Bird.Ringing.Data.2017.-.18.xlsx)

child of #5

**Comment by dimasciput** [comment]
Formatted bird data : 

[limpopo-bird.csv.zip](https://github.com/kartoza/LEDET_BIMS/files/2213334/limpopo-bird.csv.zip)

**Comment by gubuntu** [comment]
I uploaded and got 'Collection added 0 '

I searched for 'Quelea' thinking they might be duplicates: no search results

I clicked around on the map in that area - no luck - the search, click, view results in side panel still needs a lot of work, I hope there are a lot of PRs in the queue that will fix this quickly on testing

**Comment by gubuntu** [comment]
@NyakudyaA uploaded successfully in https://github.com/kartoza/LEDET_BIMS/issues/20#issuecomment-412849065
