### ISSUE TITLE
fish data to upload

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#142]
try to upload this in the fish module as excel,ods or csv

Take note:
> Here is one Stan Rodgers' files w.r.t. fish data. The fish data is under the 'fish survey' tab and the first two tabs have information on the monitoring sites themselves.

> I know that Stan would prefer to include absence data too, so we'll most likely need to update the data to include a matrix of taxa that were not caught at any site and then filter out 0 abundance data for map display.
- this part will need a new issue!

[Olifants river sites 2014 v2 .xlsx](https://github.com/kartoza/LEDET_BIMS/files/2164410/Olifants.river.sites.2014.v2.xlsx)

child of #5

**Comment by dimasciput** [comment]
going to convert this data to standard format

**Comment by dimasciput** [comment]
[fish_survey.zip](https://github.com/kartoza/LEDET_BIMS/files/2235341/fish_survey.zip)

**Comment by gubuntu** [comment]
tried to upload and got:

'There was a problem loading this page'

btw the file has no extension.

**Comment by dimasciput** [comment]
Tested in local and it worked correctly, 

File with the csv extension : [fish_survey.zip](https://github.com/kartoza/LEDET_BIMS/files/2547066/fish_survey.zip)
