### ISSUE TITLE
navigation UI

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#149]
- [x] The burger and profile menus take up the whole screen. I think they would look better taking up about 1/3 of the screen.

- [x] the menu strapline 'made with ... by kartoza' doesn't do it for me. Is the Kartoza logo in the middle supposed to stand for 'love' or 'FOSS'? It needs to be made much more obvious otherwise it reads wrong.

**Comment by carina1000** [comment]
1. Hi @gubuntu I do think it looks better covering the whole screen as 1/3 cuts the image behind and makes the screen look busy. Maybe we can utilise the screen space and add some more purpose messaging or contact information? 
However - I have designed a smaller option here: https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a2e49b9e2 

2. The strap-line is meant to only have the Kartoza symbol as in the mockups (not the whole vertical logo cc. @dimasciput ). The symbol is then read as a heart - and you are meant to read it as 'Made by "love" by Kartoza' (to use for all of the products we build in the future as our little signature) cc @timlinux 

If you both agree it's too vague I have made a more obvious one here: https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a38e623ca

**Comment by gubuntu** [comment]
1. I do prefer the smaller one - it is more usual to do it like that. 
1. Your new strapline is OK but we can keep the original one if it's made much more obvious (getting the 'love' message)

**Comment by carina1000** [comment]
@dimasciput I have made smaller burger pop up in the mockups that you can implement.
and a more obvious strap-line "LBIMS | Limpopo .... powered by Kartoza"

**Comment by gubuntu** [comment]
items in review should be deployed to testing (or I propose we add another waffle column for testing)

**Comment by carina1000** [comment]
Please implement https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a2e49b9e2

**Comment by gubuntu** [comment]
another reason the menu popups need to be smaller is so that you can click somewhere else or on the other menu to close. At the moment you have to click on a menu item or the x to close.

**Comment by carina1000** [comment]
I have made designs for these
![screen shot 2018-08-07 at 10 32 49](https://user-images.githubusercontent.com/35214829/43764251-4a19fe78-9a2d-11e8-8d9a-0fbece94e3a1.png)
![screen shot 2018-08-07 at 10 32 57](https://user-images.githubusercontent.com/35214829/43764252-4a386f84-9a2d-11e8-86fa-e01231a4cb7f.png)

 https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a2e49b9e2

Please hand over to relevant developer and implement @dimasciput
