### ISSUE TITLE
VPN needs to be sorted out

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#164]
from demo 5 July

**Comment by gubuntu** [comment]
Errol is busy with VPN, ssh, public IP etc. 

the second server should be set up in the LEDET office with the other one and also given a static IP and have rancher-agent set up and Kartoza notified. Then Kartoza will spread the Rancher orchestration across both servers. 

Then at some point LEDET will move the servers to Mokopane SITA - this must be planned properly.

**Comment by gubuntu** [comment]
Errol has moved both servers back to LEDET as he deemed that is the best location for deployment at the moment. He is busy with support from @timlinux in prepping them for deployment.

**Comment by timlinux** [comment]
Machines are prepped with Rancher client and show in our rancher server. Is there anything else needing work? We need to clarify who will do the server admin of these hosts....

**Comment by gubuntu** [comment]
Errol needs to assign public static IPs to both machines and to point bims.ledet.gov.za to one

**Comment by gubuntu** [comment]
everything working fine over VPN (and locally)
