### ISSUE TITLE
manage document and bibliography permissions

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#165]
It must be easy to assign permission to a group to upload documents and edit biobliographic records

from demo 5 July:
> Group Bibliography admin into a single group

depends on #37
child of #71

**Comment by dimasciput** [comment]
@gubuntu, Apparently right now you can only edit and create bibliography record from admin, so should we create user interface to do this? 

@sonlinux can you handle this one? Since you are the one who create the bibliography feature

**Comment by sonlinux** [comment]
Okay @dimasciput I will
thanks

**Comment by dimasciput** [comment]
Thanks @sonlinux !

**Comment by sonlinux** [comment]
@gubuntu how do you propose we approach this?
Right now we have the permissions managed in admin for bibliography.
And the bibliography models are grouped into a single app like *Bims*.

**Comment by gubuntu** [comment]
@sonlinux this issue is not in this sprint, please finish your in progress issues then ask for more
