### ISSUE TITLE
add alternative background layers to site admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#166]
from demo July 5:
> On the add site page - there is a need to have multiple background layers to use for validation.

@Vince_Egan to supply list of layers (can be public or from local GeoNode)

A user who uploaded records needs to have permission here, as well as a validator. 

This can be fulfilled in Django Admin or in a custom view, depending on how we implement the validation workflow

depends on #21
depends on #23
depends on #24

child of #24

**Comment by cchristelis** [comment]
# Note 

this needs to be applied to the validation page.

**Comment by dimasciput** [comment]
since we do validation directly on the map view, this ticket is not needed anymore
