### ISSUE TITLE
deploy tagged release off master  to LEDET production server

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#168]
Errol at LEDET has set up rancher-agent on one of the on-site servers and it is registered on rancher.kartoza.com

As a test run, deploy staging to this server and let's get some locals to try it out on their LAN

Thereafter, we update it based only on tagged releases from master (which is deployed on staging)

Therefore, it will get GeoNode once the integration has been tested on testing,  merged into master and deployed onto staging and has incorporated #158

**Comment by dimasciput** [comment]
deployed to production server

**Comment by dimasciput** [comment]
deployed with tag release
