### ISSUE TITLE
cluster, site, species

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#169]
from demo July 5:
> When you zoom into grouped data, if the data are at the same site, you can’t split the group to get specific information.

i.e. you would expect the site symbol to explode to show different species or at least classes, so you can click through to query a specific record

@Vince-Egan can clarify

**Comment by cchristelis** [comment]
please hand over to @meomancer when done

**Comment by Vince-Egan** [comment]
@cchristelis @gubuntu  Do you need further clarification here? We need multiple records at a specific site to explode into individual records that can be clicked on to source the specific information for the record.

**Comment by carina1000** [comment]
My suggestion is when zoomed in and hovered over site a pop up appears with a table that shows the Module # and Species # in that site - the user can then see the data in that site and click through the pop up to navigate to specific information on that record.

(I feel as though this is a cleaner approach than the planet/explode option)


![Map_-_clustering.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c5958a1ccfbcaa83fcac57a14ff99a2e046b313916ac217586f76ae5002e000e0b4fad470a5942a8aa8c2aa6b63d228f0858e9d2684d68d47f40f2ecdd42e64bef62994597b7b5804dc5eb3f26e38b8d48371d041f9bb2.png)

**Comment by gubuntu** [comment]
Rather (Taxonomic) Class rather than module per se since most LEDET records will for now be in the generic module, but Class is still an important classifier.

**Comment by carina1000** [comment]
![map_-_clustering](https://user-images.githubusercontent.com/35214829/43122508-9294485a-8f21-11e8-85f8-0cba00094e34.png)

**Comment by Vince-Egan** [comment]
@carina1000 , @gubuntu - this approach is great and straightforward for folks to grasp.

**Comment by carina1000** [comment]
We have decided to minimise the pop up info and rather show this on the side panel - now ready to implement @meomancer 

![Screen Shot 2018-08-01 at 15.24.46.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a379ea0c2955415b48be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb5bf749e84453a7103f6bf43b.png)
![Screen Shot 2018-08-01 at 15.24.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a379ea0c2955415c49be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb5bf749e84453a7173661f43b.png)

**Comment by carina1000** [comment]
For the Spatial Result:
-Site Details
-Dashboard
-Taxon List
-References

(the single Taxon result will look different)

See mockups here: I will slowly release population of these (still figuring some aspects out): https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a71e0d495

**Comment by Vries14** [comment]
Able to query a specific txaon class record of sites trough the side panel under "species details".
