### ISSUE TITLE
split amphibians from reptiles

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#170]
from demo 5 July

each module should be modelled at biologcal Class level. 

we only had 'reptile' data to look at, that was uploaded through the 'Reptile' module. 

However there were amphibian records in there. 

Should the user split them or should the app match records to Class?

Also, do we go ahead and create skeleton modules for every class up front? The system must be able to handle records from any class before delivery...

@timlinux provide input

**Comment by gubuntu** [comment]
For now let's just use base collection class, but the system and user must be able to distinguish the taxonomic Class. For example, in this case, amphibians must not be ingested into the Reptile module. So either the use must separate them before uploading, or the system must be able to discriminate and save them into the appropriate models. 

Varous places in the UI need to summarise or show Class so it should already be handled in the BIMS.

**Comment by dimasciput** [comment]
example of the taxonomy data :
![Screen Shot 2018-07-26 at 5.29.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56bdb607e3f0dc0e00ac2dac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f56b7191a37df110224f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ebc80395e75c06f17aaecd11abe01ba21d94ad1e5b88949d2f42f67b6d5db1063474f4dcbed5727a29841c95df549e74d55ad1b3260e5712431.png)

**Comment by gubuntu** [comment]
covered by #108

generally redundant without modules, as long as we handle Class correctly
