### ISSUE TITLE
check layer attribution

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#172]
Topo sheets base layer has the wrong attribution information. It should be NGI. 

Please check that the other layers' attributions are correct.

**Comment by cchristelis** [comment]
@NyakudyaA, please assign this to @meomancer when done.

**Comment by NyakudyaA** [comment]
@meomancer  please add the following

**Positron** 
attribution: 'Data from <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors; tiles from <a href="uni-heidelberg.de/openmapsurfer/">MapSurfer</a>, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'

**OSM Map Surfer**
attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @University of Heidelberg</a> &mdash; Map data:&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'

**Dark Matter**

attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy;<a href="http://cartodb.com/attributions#basemaps">CartoDB</a>' 

**TopoStyle**

attribution: '&copy; <a href="http://www.ngi.gov.za/">National Geo-spatial Information (NGI)</a> contributors'

**Comment by NyakudyaA** [comment]
```
Positron 
attribution: 'Data from <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors; tiles from <a href="uni-heidelberg.de/openmapsurfer/">MapSurfer</a>, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'

OSM Map Surfer
attributions: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @University of Heidelberg</a> &mdash; Map data:&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'

Dark Matter

attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors © <a href="http://cartodb.com/attributions#basemaps">CartoDB</a>' 

TopoStyle

attribution: '&copy; <a href="http://www.ngi.gov.za/">National Geo-spatial Information (NGI)</a> contributors'
```

**Comment by NyakudyaA** [comment]
Klokantech
```
Data from <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors; Tiles &copy; <a href="http://KlokanTech.com">KlokanTech</a>
```

**Comment by NyakudyaA** [comment]
@meomancer have you updated the attribution. Please close if you have done so

**Comment by gubuntu** [comment]
this is not correct on testing

**Comment by NyakudyaA** [comment]
@dimasciput Please implement

**Comment by Vries14** [comment]
Attributions fixed
