### ISSUE TITLE
improve biome and vegmap layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#173]
from demo July 5:

please remove the current biomes layer, it is poor quality. 

Rather use the vegmap biome class to create a biome layer (which is how you had vegmap styled initially) - but without borders.

Then style vegmap according to the official vegetation style and labels abd publish separately as the vegmap layer.

**Comment by NyakudyaA** [comment]
@meomancer  please change the reference for the Biome layer to come from 
URL: http://lbimsgis.kartoza.com/geoserver
Layername: geonode:biomes_of_south_africa

The vegetation map will be styled using the specification from the BGIS

**Comment by gubuntu** [comment]
Much better @NyakudyaA but there are still white borders between polygons.

**Comment by gubuntu** [comment]
OK leave it for now and move back to Ready, near the bottom, there are higher priorities.

I think the only solution  to the hairlines is to set the boundary colour to be the same as the polygon colour. 

Also, bioregion is different to biome. So you could pull out a bioregion layer as well.

**Comment by meomancer** [comment]
@NyakudyaA @gubuntu 
current version, we setup using admin

![selection_037](https://user-images.githubusercontent.com/4530905/42922163-ac1ab47a-8b49-11e8-8c9e-04ae70019af6.png)
![selection_036](https://user-images.githubusercontent.com/4530905/42922164-adad9f14-8b49-11e8-82d5-92cd3d9f2827.png)

**Comment by NyakudyaA** [comment]
The legend for the veg map is very big. I have added an issue/enhancement in geonode
https://github.com/GeoNode/geonode/issues/3850

**Comment by gubuntu** [comment]
The UI might be a GeoNode issue but a contextual legend is a GeoServer issue - I don't think it can do one. 

These layers are much better now...nice. Except shouldn't the vegmap polys have labels at a large scale?

And are the layers going through GWC for BIMS?

**Comment by NyakudyaA** [comment]
In order to generate a contextual label, you have to specify the bounding box for that getlegend request. Geoserver can do this and I think it might be an easy thing to do for Geoserver.
The vegmap style from BGIS did not have any labels but I can add it.

The layers are passing through gwc. I can seed the vegmap as it is busy with the style attached

**Comment by gubuntu** [comment]
don't worry about labels, it'll just be a time sucker, there are higher priority things to do right now

**Comment by NyakudyaA** [comment]
All layer legends conform to the source colour ranges. Will add the labels later
