### ISSUE TITLE
search fuzziness

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#176]
from July 5 demo: 
> search needs to be forgiving with spelling and case errors

child of #31

**Comment by ann26** [comment]
![peek 2018-07-27 08-34](https://user-images.githubusercontent.com/26101337/43296860-21d6cc6a-9178-11e8-976d-6bfcf55152aa.gif)

**Comment by dimasciput** [comment]
@gubuntu please this on the testing, if you satisfied of the result then we can put it on the done.

**Comment by gubuntu** [comment]
better, but

- testing this I found that #235 results from searching for 'agama' rather than 'Agama'. Results are returned in both cases but in the first they don't draw in the second they do. However in the first if you drill down, then results do draw.
- 'AgaNAs' returned more results than 'agama', which returns more results than 'agamas'

surely plural shouldn't contrain the search but should just be part of the fuzziness (extra letter versus incorrect letter)...I think the search fuzziness could do with a little more tweaking

**Comment by Vries14** [comment]
- Results draw with case errors
- incorrect letter part of search fuzziness
