### ISSUE TITLE
Point locality data should be reported for cursor position on the map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#178]
from demo July 5

@Vince-Egan please elaborate

**Comment by Vince-Egan** [comment]
@gubuntu: when you move the cursor around the map, you should be able to see the decimal coordinates of the cursor somewhere on the screen.

**Comment by gubuntu** [comment]
Ah, that's already done. If you click the icon in the bottom left it shows the dynamic mouse coords
