### ISSUE TITLE
change remote map layers to local reference

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#180]
depends on #158

Once the GeoNode branch has been merged with develop and the data currently on lbimsgis has been restored into it, refactor all WMS layers in the BIMS map to use the integrated GeoNode (with authentication obeying role permissions)

child of #4
depends on #27

**Comment by cchristelis** [comment]
Let's add a model in the DB that admin users can assign the sources and what the context data is called.

**Comment by dimasciput** [comment]
We get layers from geonode and admin now.
