### ISSUE TITLE
update map UI

### ISSUE THREAD

**Issue by ann26** [kartoza/LEDET_BIMS#182]
following up #136 

- [x] The initial map page view is rather abstract. I think it needs an info popup on load that explains the default view and what you can see and do, along with the purpose, with a 'don't show this again' option. 
- [x] default zoom to Limpopo Province

related to kartoza/django-bims#155

**Comment by timlinux** [comment]
For the second item (cluster cartography) see also https://github.com/kartoza/django-bims/issues/155

**Comment by carina1000** [comment]
Fo the first item please see https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a85920f2a

And suggested copy can be found in https://docs.google.com/document/d/1VglbMPJz0Ys7gRGkjZgJP4Nb0wpraHkg9Cuq9rK-EQQ/edit (but this might change as we refine the system)

**Comment by gubuntu** [comment]
@ann26 the info popup could simply fetch content from the /aboutus flatpage. Then it's simple to maintain.
