### ISSUE TITLE
Propose right panel info solution

### ISSUE THREAD

**Issue by carina1000** [kartoza/LEDET_BIMS#183]
# Problem

Currently the data is showing both on the right panel (search results) and a pop up.

# Solution

We need to keep the info on the right panel and come up with some sort of conceptual hierarchy. 

Parent of #169
child of #31

**Comment by carina1000** [comment]
@gubuntu please confirm the proposed "conceptual hierarchy"

**Comment by Vries14** [comment]
Pop-up ( for sites) removed. Info displayed on right panel.
