### ISSUE TITLE
FR10 upload biodiversity data with geometry

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#184]
this refers to standard biodiversity observation data ('distribution' refers to the location as xy point coordinates or polygon) i.e. the generic biodiversity record class.

In this ticket, handle upload from shapefile. also see the requirements document for further context.

GeoPackage or GML  or even GeoJSON are preferable to shapefile unless they take longer to code. We want to be standards compliant rather than just go with shapefile because it is ubiquitous.

While #5 will handle most cases (all cases with point geometry as x/y or long/lat)), this is specifically for users who have data with geometry already and especially for records with polygon or line geometry, which are not handled by csv. All other fields should be the same as for csv (except no x/y or long/lat)

child of #5

For testing:

[fishshapefile.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46ee9d892b918ba89fecb94aa858b2d86b56357c2301a03f32dfa17dbe437f505e591caa470c0c41fdf9892af4b368238e5f0effcd7f1d2598694ef1e1c84afd13b032894f8fb7b9894fc6ed3526ef88894e3a0c48.zip)

[birdshapefile.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46ea9d8827918ba89fecb94aa858b2d86b56357c2301a03f32dfa17dbe437f505e591caa470c0c41fdf9892af4b368238e5f0effcd7f1d2598694ef1e1c84afd13b0328a488fb7b9894fc6ed3526ef88894e360c48.zip)

**Comment by dimasciput** [comment]
- [ ] with fish and birds, got 'Added 0 collections', show duplicated data ( redundant https://github.com/kartoza/LEDET_BIMS/issues/142 ) 
- [ ] What if CRS is different than 4326? If you don't handle other CRS then the shapefile and csv upload dialogue must say 'coordinates or geometry must be geographic on WGS84 datum'
- [ ] make csv and shapefile dialogue layouts consistent, e.g. put the file picker in the same place.
- [ ] for shapefile, tell the use to select the shp, shx and dbf files.
- [ ] 'upload another files' should be on both dialogues and should read 'upload another csv file' or 'upload another shapefile'
