### ISSUE TITLE
do full geonode backup of lbimsgis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#185]
do a full backup and sync or share so it can be restored on testing and dev machines (and then staging when staging has geonode)

required by #158
required by #159

**Comment by NyakudyaA** [comment]
Done the full Geonode backup. Still syncing the database dumps from the server.
Setup the share using the following key
*RO* : `BTGIPZLB3U7IS6OJKRICGJAFYXBI7STWI`
