### ISSUE TITLE
activate or remove home page dashboard

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#186]
The home page icons are static demos. They should show real information or be removed or replaced. 

I propose showing summaries per taxonomic Class as well as numbers of layers in GeoNode for the other LEDET departments

**Comment by gubuntu** [comment]
leave it (and #226) in backlog. We'll do it in the last sprint.

**Comment by Vries14** [comment]
- Icons replaced , no longer static demos
- taxonomic class summaries used for the information inside graphs
