### ISSUE TITLE
several links leave BIMS

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#188]
e.g. login opens a new tab. This is a one-page app...

**Comment by Vries14** [comment]
Since this is a one-page app, should the gbif.org links in the side panel open new tabs?
Because for each taxas' gbif.org link a new tab opens.

**Comment by gubuntu** [comment]
yes external sites must open in new tabs

but all internal links should open in the same tab - that's what you need to test.

**Comment by Vries14** [comment]
Internal links are opening in the same tab

**Comment by Vries14** [comment]
When I uploaded a new record and clciked on the "verify records here" link, it opened in a new tab for validate records.

**Comment by Vries14** [comment]
Not opening a new tab anymore
