### ISSUE TITLE
UC1 Secure Connection while Browsing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#19]
_From @cchristelis on May 22, 2018 14:35_

# Use Case

## Actor

All users

## Description

While the user is using the site, all traffic is SSL secured.

## Preconditions

- 

## Process Flow

1. The user has navigated to the site.

## Exceptions

1. Man in the Middle attacks etc.

## Business Rules

1. Can we use letsencrypt or are we going to get a authoroty to sign the certificate?

## Assumptions

1. The user uses a modern browser, which is able to handle the cipher, which is negotiated.

_Copied from original issue: kartoza/LBIMS#3_

**Comment by timlinux** [comment]
@dimasciput this one is for you. We will create a separate container for certbot and mount the certs into the nginx container via a shared volume with the certbot container.
