### ISSUE TITLE
handle duplicates on upload

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#198]
We say in the upload UI that duplicates are detected and rejected, but are they? If so, how? and what is the interaction?

# proposal
identify candidate duplicates on upload and flag them so that the user or validator can choose which if any to delete

candidate duplicates must match on site AND time AND species AND collector/observer

child of #5

**Comment by cchristelis** [comment]
Please ensure that this logic is in place.

**Comment by dimasciput** [comment]
If same data, collection will not be added 
![Screen Shot 2018-08-01 at 3.56.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56bdb607e3f0dc0e00ac2dac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a37bf1172d4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ebc80395e75c06f17aaecd11abe01ba21d94ad1e5b88949d2f42f67b6d5db1063474f4dcbed5727a19041c95df548e04c56ac103667e3702431.png)

**Comment by gubuntu** [comment]
If I get 'Added 0 collections' how do I know it's because of duplicates or that it just didn't work?

If the fish and bird uploads I tried were duplicates it would be nice to automatically go to them as a search result (new ticket in Funnel...) but at least I should be able to find them by manual searching or browsing. I found that difficult if not impossible.

**Comment by dimasciput** [comment]
@gubuntu So what did you suggest ?

**Comment by gubuntu** [comment]
- change 'collection added' to 'records added'
- If any were uploaded but not added, add a message with a reason, like '39 duplicates were not accepted'

then close...

**Comment by Vries14** [comment]
- Duplicates gets rejected.
- message for rejection of duplicates are showing.
- "records added" message showing.
