### ISSUE TITLE
Enable django data exports of biodiversity layer

### ISSUE THREAD

**Issue by meomancer** [kartoza/LEDET_BIMS#200]
# Problem
User should be able to download current data in view.

# Solution
- [x] Create control `download button` and show format that user want
- [x] Download data based on filters and view

child of #32

**Comment by dimasciput** [comment]
For CSV and Geojson

**Comment by gubuntu** [comment]
- csv works nicely
- no geojson yet (not required in OP, make another ticket for it in funnel)
- button needs tooltip
- change 'Select a format to download current data.' to 'Select a format to download the biodiversity data you see on the map. Many records may take time'

almost there!

**Comment by Vince-Egan** [comment]
It doesn't look like the spatial info is mapping to the lat/long fields. There is also no data in the location_site field, but this may be because there is no data there.

**Comment by dimasciput** [comment]
@Vince-Egan that has been fixed in testing server, please test again

**Comment by Vries14** [comment]
- [x] info on csv  showing lat-long fields, location_site 
- [x] When I apply more than one filter though, the csv don't download and gives me a "data is empty" message, for example: I searched for berg and applied the "translocated"  category filter. I got 38 records. When i tried to download the csv file I got "data is empty".If there is records, shouldnt those be downloading?
