### ISSUE TITLE
Update Context Documents

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/LEDET_BIMS#205]
- [x] Update model for handling location context document
- [x] Add model's method to update location context document
- [x] Implement management command to update context document for all LocationSite
- [x] Implement signal when a LocationSite is changing its location, then update its context document

**Comment by gubuntu** [comment]
@ismailsunni please update waffle status of this issue

**Comment by ismailsunni** [comment]
The PR is merged, please review/test it.

**Comment by gubuntu** [comment]
please assign to the person who shoud review it
