### ISSUE TITLE
UI Design to Show Context

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/LEDET_BIMS#206]
- [ ] Design the UI, discuss with others (@carina1000 or @dimasciput )
- [ ] Implement it

**Comment by timlinux** [comment]
@ismailsunni 👍 
@carina1000 and I have been working up the UI for context. Can you please work up this into a standard panel view that will go into the accordion. It will be associated with a site (point geometry). Where a site is a polygon we could use the centroid of the site - ok with that @gubuntu ?

![screen shot 2018-08-01 at 10 46 36](https://user-images.githubusercontent.com/178003/43511375-82c294d8-9578-11e8-9add-e0038ec1f593.png)

If you prefer you could separate the temp and rainfall into two separate charts. 

You need to ensure that we have the context collection to support all these fields (except for description which will come from the sites model). Work with @kartoza/admin-staff to ensure that any layers listed (e.g. aspect and slope).

**Comment by timlinux** [comment]
Also evertyhing except the Climate (which has special behaviour rendering charts) and the description (taken from sites model) should be automatically rendered not hard coded so that if we change the collection the context panel will update. If you can manage to tweak the collection to indicate that a group is a 'graph group' so we can generically render charts (e.g. one group each for min, max, mean temp and mean rain giving us 4 charts) that would be cool too.

**Comment by timlinux** [comment]
So we took a big step forwards for this today - thanks! 

Can you see why there are missing months in some contexts? Maybe Admire has to add some months in the context list:

<img width="261" alt="screen shot 2018-09-04 at 23 37 33" src="https://user-images.githubusercontent.com/178003/45059211-886c0480-b09b-11e8-82c0-287b4946166c.png">

It would also be great if we could round temperature and rainfall to 2 decimal places

**Comment by NyakudyaA** [comment]
@timlinux I will process the datasets to round them up to 2decimal places. I initially just published them as they were because I didn't want to introduce any artefacts.

**Comment by gubuntu** [comment]
1 decimal place would be even better

**Comment by Vries14** [comment]
UI for site details implemented
![site deatails](https://user-images.githubusercontent.com/42169058/45879063-6c5aa980-bda3-11e8-96c6-7a1ed0b60b10.png)

One decimal place added for rainfall and temperatures on graphs
