### ISSUE TITLE
Mockup Documents and Reports Page

### ISSUE THREAD

**Issue by carina1000** [kartoza/LEDET_BIMS#210]
Mockup Resources Page

child of #71

**Comment by carina1000** [comment]
![Documents__Reports.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cc9b99368f86a79bfa807c9658e09b3b5234316546b3397f8fe62bab0021435a0e1ff840595916faffdd78a3b73c708b0e0eb982695c71d42103eee9dc4be05ce36ade0d97bcae884dcae93826e48b8c4b3e1b05118afe4f78.png)
![Documents__Reports_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cc9b99368f86a79bfa807c9658e09b3b52344c7846ef696097ec22ba416f43554d4bfd100c5e45faab8f2df2e539718a5c0abfd4390c70c53803b0aac04ee155e57dd205d0f4ae805ec1e03724e2888c4f3d1a051d8cfa5434b2d4.png)

https://app.moqups.com/tim@kartoza.com/47tU30vEA3/export

**Comment by gubuntu** [comment]
why closed? 

I like the layout...each item needs to be referenced in the bibliography component  (e.g. hover or click on 'reference' link) and if it is linked to a site or observation, to also have the option of going to that record on the map. 

Conversely, from the map, if a site or observation has a linked resource, to list them in the side bar (add to this morning's discussion) and if the resource is an image, to be able to see it in context e.g. as a popup.

**Comment by carina1000** [comment]
The files linked to the map will be displayed on the right side pannel under the "Resources" accordion
![Screen Shot 2018-08-01 at 15.39.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f26b7191a379ea0c2858415e49be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5f37aa984ecb5bf748e14556a71a3163f43b.png)

**Comment by gubuntu** [comment]
Think of the bibliography as the catalogue of resources, of metadata about resources. 

And think of resources as documents, images, videos, biodiversity records etc. 

So the map and resources page are two ways of viewing resources. On either of these it should be possible to discover the metadata (reference / bibliography) pertaining to a resource and to discover linked resources. 

Then conversely one can also have a catalogue view of the bibliography and from there view the resource(s) an entry describes. 

When it comes to implementation:
- we have the bibliography app 
- GeoNode can store documents (any media file)
- the BIMS stores biodiversity records

so these need to be hooked together...

**Comment by carina1000** [comment]
@gubuntu I understand the first bit and then you lost me. 

Don't the mockups fit the criteria? Where did I miss it?
