### ISSUE TITLE
FR49 search must index municipalities

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#211]
> The LBIMS shall enable a user to upload, download and view biodiversity data per local and district municipality from the UI, in support of IDPs and SDFs.

child of #31

**Comment by dimasciput** [comment]
![screen shot 2018-08-27 at 10 59 13 am](https://user-images.githubusercontent.com/1979569/44639846-49c5b280-a9e8-11e8-922b-a2563cd2bfd1.png)

**Comment by Vries14** [comment]
Users are able to upload, download and view data in a district or local municipality
