### ISSUE TITLE
admin layer is still drawing under the base map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#223]
- [ ] it should draw over the base map
- [ ] its style should be defined in Geoserver
- [ ] it should be coming from GeoNode/Geoserver

**Comment by dimasciput** [comment]
@gubuntu which one is admin layer?

**Comment by gubuntu** [comment]
The only other layer that's in the map at the moment: 'administrative'

**Comment by dimasciput** [comment]
This is not a bug, we just haven't merged it yet to the develop branch : https://github.com/kartoza/django-bims/pull/144

Currently irwan is still updating his PR.

**Comment by gubuntu** [comment]
OK happy to close then
