### ISSUE TITLE
Upload shows no previews on Geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#225]
# problem
I have just updated a style in GeoServer and the style should propagate to Geonode but the preview is not coming through.
Also Updated a bunch of layers using the management commands and the thumbnail is not working
![thumbnails](https://user-images.githubusercontent.com/2510900/43706771-91c71d22-9966-11e8-9baa-4f04737ba538.png)

**Comment by gubuntu** [comment]
@NyakudyaA I assume this is in testing because it is fixed? Please confirm on the testing server and close if you're happy

**Comment by NyakudyaA** [comment]
@gubuntu I fixed all the other thumbnails when I updated the metadata. This issue still exists when a user uploads a new layer from either through the management commands or the UI (still uploads are not working through UI)

**Comment by gubuntu** [comment]
I've moved back to in progress assuming you're troubleshooting it

**Comment by NyakudyaA** [comment]
@dimasciput cc @lucernae I have tested this and I think it is related to the uploads not working properly.
But for layers loaded using the management commands I think the generate thumbnails script/signal is not running.

**Comment by NyakudyaA** [comment]
@ismailsunni on testing uploads are showing a different error now.
![upload.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46fd84962c8387ebc3abaf51ab57f5973d047d317c05a22f21d4b52ae9147f025a5e4eac400a5a10affd8a2eb4aa2e32db025fb28c341521842f1bbeb98b15be04b924884b81bfb98a4dc9e82f68.png)

**Comment by ismailsunni** [comment]
@NyakudyaA I can not upload the layer properly in my local dev env also.

For the duplicate key, what I did is deleting hiearachicalkeyword from admin panel. THe error is gone, but I still can not upload layer to geonode (it's update the geonode db, but not uploaded to the geoserver).

**Comment by NyakudyaA** [comment]
All uploads show thumbnails. tried using the UI and the management commands.
![staging](https://user-images.githubusercontent.com/2510900/44414562-5f615500-a56e-11e8-9fa9-9351c982f9a6.png)
