### ISSUE TITLE
response when clicking anywhere on the map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#229]
at any time, if the user clicks anywhere the system returns a drill-down'getfeatureinfo' response as a popup

This is in addition to the biodiversity side-panel response if there is also a biodiversity site in the click radius

**Comment by meomancer** [comment]
hi @gubuntu 
is this the right request for getfeatureinfo?
```
https://testing.limpopobims.kartoza.com/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&layers=geonode%3Abiomes_of_south_africa&format=image%2Fpng&INFO_FORMAT=text%2Fhtml&buffer=10&I=41&J=147&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=2348145.5089206137%2C-4070118.8821290657%2C2504688.5428486546%2C-3913575.848201025
```

it returns 
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://testing.limpopobims.kartoza.com/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="LayerNotQueryable" locator="QUERY_LAYERS">
Either no layer was queryable, or no layers were specified using QUERY_LAYERS
</ServiceException>
</ServiceExceptionReport>
```

**Comment by Vries14** [comment]
The popup is supposed to show when any point on the map is clicked, but when clicking on administrative texts the popup fails.

**Comment by dimasciput** [comment]
@Vries14 @gubuntu yes that was done intentionally, since we're going to zoom in when we click the cluster. What do you suggest @gubuntu ?

**Comment by gubuntu** [comment]
I think @Vries14 is talking about clicking on an admin boundary label rather than on a cluster. 

Click on cluster or site has well defined behaviour. 

Click anywhere else should do the GetFeatureInfo drilldown.

**Comment by cchristelis** [comment]
It would be great to have this activated through a tool button.

**Comment by cchristelis** [comment]
This should also be available on healthyrivers.

**Comment by Vries14** [comment]
Clicking on map gives info pop-up
