### ISSUE TITLE
zoom to single search result too close

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#236]
I clicked on a 'biological collection record' after a search and it zoomed to the site but there was no context with any basemap - it had zoomed in waaaay to close. Zoom to a single record should be limited to zoom level 18 perhaps.

**Comment by meomancer** [comment]
fixed by kartoza/django-bims/pull/205

**Comment by gubuntu** [comment]
move to testing if ready to test

**Comment by Vries14** [comment]
Clicking on "biological collection record" zooms in to a useable level in context with map.
