### ISSUE TITLE
legend draws under other controls

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#238]
![screen shot 2018-08-08 at 15 35 19](https://user-images.githubusercontent.com/496911/43840442-05e5317e-9b21-11e8-8003-e55ac9e09837.png)

**Comment by gubuntu** [comment]
working now

**Comment by gubuntu** [comment]
not working now

**Comment by Vries14** [comment]
Legend is now drawing over other controls,
![screenshot_2018-09-12 django bims map](https://user-images.githubusercontent.com/42169058/45408257-20ee2000-b66c-11e8-8d66-f060849f9052.png)

**Comment by dimasciput** [comment]
@Vries14 I think that's what gavin wanted

**Comment by Vries14** [comment]
If this is the case then im closing the issue.

**Comment by gubuntu** [comment]
this is better, but it's really a part of making the whole app responsive, so all elements are usable in any form factor.
