### ISSUE TITLE
Error on logout from layer details page in Geonode

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#239]
# Problem
Each time I am in layer detail's page in Geonode and try to log out I get the following error.
![logout](https://user-images.githubusercontent.com/2510900/43889401-5a819d8c-9bc4-11e8-94f9-71c4307674d1.png)
If I reload the site again it shows me that I have been completely logged out.

**Comment by dimasciput** [comment]
@NyakudyaA yes because currently the logout will redirect to your last url

**Comment by NyakudyaA** [comment]
@dimasciput but should we not direct users to the landing page rather than the last URL

**Comment by Vries14** [comment]
No longer get 403 when logging out from layer page in Geonode.
