### ISSUE TITLE
Group and layer permisions are not filtering properly for layers.

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#241]
# Problem
I have assigned basic layer permissions for layers in Geonode but the rules seem to be ignored totally.
Example
![biomes](https://user-images.githubusercontent.com/2510900/43901964-1c33bd2e-9be9-11e8-8baf-5dff4e084360.png)

When accessing the Geonode in another browser I do not expect to see this layer because I have disabled anonymous viewers access to the layer. But in Chrome I see all the layers
![layers](https://user-images.githubusercontent.com/2510900/43902115-8ad10db8-9be9-11e8-9460-0499c5ce0373.png)

#68 
#63

**Comment by dimasciput** [comment]
Hi @NyakudyaA , please don't change permissions for the biomes and administrative layers because bims currently using it. You can change other layers permissions.

**Comment by NyakudyaA** [comment]
@dimasciput what I merely changed was access to the layer. Currently, any person can see the layer. When layer permissions are working properly only members of the same group can view the layer.  The permissions only restrict who can see and download layers. Bims should not be affected by that

**Comment by gubuntu** [comment]
@NyakudyaA what's the status of this now on staging?

**Comment by NyakudyaA** [comment]
@gubuntu I have tested this and this is still an issue. Tried the same setup on http://testing.geonode.kartoza.com and I can confirm it works.

**Comment by NyakudyaA** [comment]
This is now working properly on testing. On staging, it should also work properly.
After adding a user make sure that the user does not have the anonymous group permissions.
![layers.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46e49583269090ebc3abaf51ab57f5973d047d317c05a22f21d4b52ae9147f025a5e4eac400a5a10affd8a2eb4aa2e32db025fb28c341521842f1bbeb98515be04b924884d80b3bb8f4ec7e82f68.png)

**Comment by NyakudyaA** [comment]
This is working properly now. Any added user by default belongs to the anonymous group. So any layer added should have the permission changed explicitly for that layer. This includes who can see, download and play around with some other settings.

Tested a couple of layers with @Vries14 and once I changed permissions he could not access the layers.
I will close this issue.
