### ISSUE TITLE
search result interaction hanging and killing server

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#245]
I searched for 'agama'

only some things expanded when clicked, ultimately the UI hung and the site became unresponsive (like yesterday). Expecting it to end up with a 503.

**Comment by dimasciput** [comment]
@gubuntu I'm still doing backup database from testing, and it's pretty big task, maybe that's the cause, because there's no error in sentry for this.

**Comment by gubuntu** [comment]
ok, no longer hanging
