### ISSUE TITLE
allow admin to set defaults / save user's settings

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#250]
currently, when a user opens the map there will be a list of layers in the layer selector and the biodiversity layer will be switched on. 

Either an admin should be able to set which layers are switched on by default or the user's choices of which layers are switched on and in what order should be remembered between sessions e.g. in a cookie

child of #29

**Comment by cchristelis** [comment]
Tried this out, it's not deployed yet it seems.

**Comment by Vries14** [comment]
Choices of which layers are switched on and in what order they should be, are remembered.
