### ISSUE TITLE
if a validator uploads, gets no edit screen

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#253]
# problem

The upload in https://github.com/kartoza/LEDET_BIMS/issues/20#issuecomment-412849065 went straight to validator screen

# expected bahaviour

Anyone (including a validator) who uploads data should get an edit / review screen before handing off to a validator.

**Comment by gubuntu** [comment]
I guess the 'update' screen is there and it works, but maybe it should be pointed out to the user that they need to review their form captures there before sending them off to a validator

**Comment by Vries14** [comment]
Able to review and edit uploaded data before sending them to a validator
