### ISSUE TITLE
should not assign permissions at user level

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#256]
GeoNode permissions are at group level but when you add a user youget the option of assigning permissions at user level - this should be hidden - GeoNode bug?

**Comment by NyakudyaA** [comment]
Yes, this is a bug. A regression from normal Geonode behavior. Users should only have the option to choose a group
![group](https://user-images.githubusercontent.com/2510900/44140857-adcd8418-a07b-11e8-8f86-6ce49389ca38.png)
.

**Comment by Vries14** [comment]
User permissions changed to only group permissions
