### ISSUE TITLE
new superuser was not part of any groups and could not add members to any group

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#259]
surely a superuser should be a manager of all groups?

**Comment by NyakudyaA** [comment]
If a user is by default designated as a superuser their permissions are explicitly set. Adding them to be part of all groups is basically duplicating functionality. 
I have created a test superuser on the testing server and I can assign users to various groups.

**Comment by dimasciput** [comment]
Should we close this @gubuntu ?
