### ISSUE TITLE
Locate by coordinates not user-friendly

### ISSUE THREAD

**Issue by Vince-Egan** [kartoza/LEDET_BIMS#260]
using 'locate by coordinates' option on the map, the order of the two fields following the text are in the reverse order of the order they are mentioned (long and lat). It isn't clear which should be in each of the boxes. Maybe rather state negative degrees south than positive degrees north.

**Comment by gubuntu** [comment]
complements https://github.com/kartoza/healthyrivers/issues/146

**Comment by gubuntu** [comment]
fixed
