### ISSUE TITLE
Links upload and links display don't correspond

### ISSUE THREAD

**Issue by Vince-Egan** [kartoza/LEDET_BIMS#263]
When I added BIMS links on the staging server and assigned them to categories, only the first one was added to the links page. Also, the information displayed for each link should be the name and not the description. The amount of characters allowed in the name should perhaps be increased too.

**Comment by Vince-Egan** [comment]
The Links page  is responding erratically - sometimes displaying no links and otherwise only the first link that I added.

**Comment by Vince-Egan** [comment]
It looks like the issue is that only a single category is displaying. When I add more links under the category that is displaying, they appear on the Links page. It is the other link categories that are not displaying.

**Comment by dimasciput** [comment]
@Vince-Egan fixed on testing, could you try it again

**Comment by cchristelis** [comment]
We'll follow this up in another ticket if it is still an issue.
