### ISSUE TITLE
Carousel upload unsuccessful

### ISSUE THREAD

**Issue by Vince-Egan** [kartoza/LEDET_BIMS#264]
When I uploaded another carousel image through the front end, I received a confirmation of upload but the image was not added to the carousel (it appeared as a black block). When trying to edit the image via the Administration link, I got a 403 error. I can view the images that are already on the system.

**Comment by dimasciput** [comment]
I couldn't reproduce this, I managed to upload an image in staging. @Vince-Egan can you try again?

**Comment by Vince-Egan** [comment]
@dimasciput - I saved the image as a jpeg and then retried the process. This time it did upload okay.

**Comment by Vries14** [comment]
@dimasciput or @Vince-Egan , if this is working correctly and you are satisfied, could we please move this out of testing?
