### ISSUE TITLE
Geonode upload error based on projection

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#267]
#Problem 
I tried uploading an shp with projection  3857 and this is what I get
![3857](https://user-images.githubusercontent.com/2510900/44403450-c1ad5c00-a554-11e8-8e31-f9579536056a.png)

# Solution
Ensure that the changes implemented in fixing this in Geonode are part of this image

@boney-bun  can you take a look at this

**Comment by gubuntu** [comment]
looks like an issue with the extent, not the CRS?

our fixes are on kartoza/geonode and are focussed on QGIS server backend. So to fix this they would need to be tested on geoserver backend (get testinggs.geonode.kartoza.com working @boney-bun) merged upstream and then pulled into django-bims (or cherry-picked)

@NyakudyaA no 3857 data should be loaded anyway (most should be 4326 or local SA CRSs) so I would say this is low priority.

**Comment by NyakudyaA** [comment]
@gubuntu we used to have an issue like this in QGIS server. I think the codebase for reading CRS is the same wether it is QGIS server or Geoserver. When the layers are loaded through Geoserver all is fine. That's why I thought @boney-bun  could look at it and just look and compare his changes.

**Comment by NyakudyaA** [comment]
This issue is an upstream bug in Geonode. I am going to open an upstream issue for this

https://github.com/GeoNode/geonode/issues/4103

**Comment by evilGmonkey** [comment]
Is there an Eta when this will be fixed or even a patch?
