### ISSUE TITLE
Geonode uploads are now being saved as shapefiles

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#268]
# Problems
Geonode UI uploads should be stored in the database backend but now they are stored as shapefiles in Geoserver.
![biom](https://user-images.githubusercontent.com/2510900/44403844-c58dae00-a555-11e8-98bd-b551c7722d8e.png)

# Solution
Please fix we had this working before

**Comment by gubuntu** [comment]
yes this was after a fix @lucernae deployed while I was training last week - the fix allowed uploads, but they remained shapefiles

**Comment by dimasciput** [comment]
@NyakudyaA fix by https://github.com/kartoza/django-bims/pull/299, please test in the testing server

**Comment by NyakudyaA** [comment]
LGMT
