### ISSUE TITLE
FR12 display non-biodiversity data on the map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#27]
All non-biodiversity observation data will be rendered as OpenLayers WMS or XYZ layers fetched from LBIMS web map services (provided by Geoserver or QGIS server) or public web map services. 

If vector data of these layers are required they can be retrieved via WFS from these same services and rendered with SLD or MapBox JSON styles

child of #29

**Comment by gubuntu** [comment]
the list of layers is in #39. Some are already available on maps.kartoza.com and the rest are being published on lbimsgis.kartozaa.com (@NyakudyaA please get it to accept that domain). 

So you can start pulling in some layers already

**Comment by gubuntu** [comment]
@meomancer where are you configuring the layers? I didn't notice a django-wms model in admin

**Comment by gubuntu** [comment]
ping @meomancer 

Also now that BIMS is integrated with GeoNode, BIMS admin needs to configure layers and permissions - what is progress with that?

**Comment by cchristelis** [comment]
@meomancer this should be softcoded, not hardcoded.

**Comment by gubuntu** [comment]
currently none on testing and all those that were on staging have disappeared

**Comment by meomancer** [comment]
handling by @ismailsunni for getting layers from geonode

**Comment by gubuntu** [comment]
implemented as per OP
