### ISSUE TITLE
Menu and profile

### ISSUE THREAD

**Issue by Vries14** [kartoza/LEDET_BIMS#277]
# Bug report
I opened my map and I was unable to open the menu or my profile from that view. This also happens in certain other views eg. Validate records view

**Comment by Vries14** [comment]
This is still not fixed, Im still unable to click on menu and profile in the "contact" and the "validate records'
view.

**Comment by dimasciput** [comment]
@Vries14 can you try again https://testing.limpopobims.kartoza.com/contact/ ?

**Comment by Vries14** [comment]
menu and profile functioning
