### ISSUE TITLE
Signup confirmation email is sent to spam

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#279]
# Problem
When a user signs up or receives an email to confirm account signup. The confirmation email is sent to spam
![spam](https://user-images.githubusercontent.com/2510900/45616676-7eb9a800-ba70-11e8-8dc8-ea47d9af35b8.png)

# Solution
Is it possible to determine where the email gets send to - Most users will not look into the spam folder for the emails

**Comment by dimasciput** [comment]
@Vries14 can you confirm that email you got is sent to spam or not?

**Comment by Vries14** [comment]
@dimasciput , The emails for signing up does not go to spam.
