### ISSUE TITLE
FR13 Enable map panning and zooming

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#28]
These are built into OpenLayers through gestures and controls

Just ensure that appropriate controls are displayed and working

**Comment by timlinux** [comment]
Maybe add some controls for it in OL

**Comment by timlinux** [comment]
I think we can mark this as done already.


![Screen Shot 2018-06-04 at 09.49.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba456e7953d2fd0f723bdb/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f76b7191a378e60c2f58415d4ebe5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca50f642e9485da41a3160f43b.png)
