### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by carina1000** [kartoza/LEDET_BIMS#281]
# Problem

The mobile version isn't fully responsive

# Solution

![LogIn.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c49b9d0a8cc1e5cdf9ad4cae58f3806b1c65262805a77a21d3e17ee94678545e5f4ead135d0b17f8fa8c39baa47e21d40854b088270a36d43703adb1881eba02bd238f4d81beb8884dc2fa70.png)
Ensure buttons and footer are stacked correctly

![Map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c5958a61cec1b99de6b546a749b2ce6b1326722d55f27d72d3b52cbc172a515f5e1ca9150b5b47f9eb9539e4e76224d50152a7842f4d7ed43c19a6b9871cb802be228e4f86bfba885e8d.png)
Ensure that the map tools are all the way on the right side giving ample map space on mobile

![Map-search_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c5958a6e9186a89deab77cf51fbcd6395428792c07b7692ac7b629be462a50590d48aa150b5a45fcf98879a3e26f74895919f1c32f0e2a92624cf5f2d75dad0ba821834584b3bf8d4fc4ea382ce58f894e2c53.png)
Ensure that the search pannel scales correctly onto screen

![Map-search_reuslts.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c5958a6e9186a89deab77cb658e587255234316546b3397f8fe62bab0021435a0e1ff840595916faffdd78a3b73c708b0e0eb982695c71d42103eee9dc4be05ce36ade0d97bcae8b44cae93826e0888b4d381d021e8eff4f78.png)
Ensure that initial search pannel gets replaced with search result pannel *Note this is different to the desktop double pannel - the double pannel does not work for mobile

![Map_-_Dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46c5958a1ccfbc8d8efab741ab5ce2906b0a65633b0ba92e7391a172fd177a000b5e4faa135e5910affc882ba6b76e75de0f0feed47f4366846c4ff8e7df46f554f832815d84bfb68b49c3ef3e21e58c8f4d3819020ac4.png)
The dashboard works fine as it is now :)

Let me know if you need anything else!

**Comment by gubuntu** [comment]
read with #46

**Comment by Vries14** [comment]
For mobile reponsiveness...

- Cant click on menu from map view
-Cant use transparency control for layer selector
-Also I think the side panel should rather fit to window when opened, since there is an option to close it

**Comment by anitanh** [comment]
- For the menu I'm not sure why, I can click on the menu from map view on development (on my local machine) but I can't click it on staging.
- For transparency control, it is something to do with the slider which I haven't been able to fix.
- For the side panel, it is already fit to window (see below):
![screenshot from 2018-11-07 11-08-47](https://user-images.githubusercontent.com/26101337/48110260-a6add680-e27d-11e8-91fb-e01d92bf7238.png)
