### ISSUE TITLE
Change footer

### ISSUE THREAD

**Issue by carina1000** [kartoza/LEDET_BIMS#282]
Please change footer according to designs:

![Screen Shot 2018-09-19 at 09.44.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fa6b7191a378e60c2f55415f46be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5ff54fe24d52a2123e66f43b.png)
Footer for Landing page and other pages

![Screen Shot 2018-09-19 at 09.44.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fa6b7191a378e60c2f55415e49be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5ff54fe24d5ca3153162f43b.png)
Footer for map

**Comment by anitanh** [comment]
covered in https://github.com/kartoza/LEDET_BIMS/pull/301

**Comment by Vries14** [comment]
Changes to footer updated with kartoza/LEDET_BIMS/pull/301
