### ISSUE TITLE
Disable links in landing page if a user doesn't have the necessary permissions

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#286]
This ticket referee to the UI/UX roles

* When a user is not logged in he/she can access all menu's even the one's that requires login. The site details requires a user to login before seeing this. Can we remove this from the menu when users are not logged in.
* When a user clicks the site details he/she is directed to the login page and then after login in the page stays the same and a message pops up saying a user is logged in. Rather let's send a message to say you are not allowed to to view this menu or rather do not show this menu if a user does not have permission for it.
![screen shot 2018-09-20 at 20 01 28](https://user-images.githubusercontent.com/2510900/45837870-a464dc80-bd10-11e8-92ed-9f26fed1ca88.png)

**Comment by Vries14** [comment]
-While being logged out,  and clicking on site statistics and logging in from there, the message still pops up that says user is loggen in

**Comment by Vries14** [comment]
landing page view updated so that users that not logged in cant see site statistics
