### ISSUE TITLE
Unable to navigate to other menus from the contact us page

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#287]
# Problem

From the home page a user is unable to navigate away from the contact us page. All buttons for other menus become inactive.

![screen shot 2018-09-20 at 20 11 50](https://user-images.githubusercontent.com/2510900/45838286-a8ddc500-bd11-11e8-897b-de84fa41ebe9.png)

**Browser** : Safari

# Solution
Please fix

**Comment by gubuntu** [comment]
fixed
