### ISSUE TITLE
implement formal release management and tag  and deploy production release

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#288]
1. __BEFORE TUESDAY 25 SEPT__ give django-bims and LEDET BIMS their own independent release tags and deploy to production will all the latest tested work 
1. Ensure all django, geonode, geoserver etc. content is successfully migrated
1. Name versions according to what should be standard Kartoza semantic versioning principles.

**Comment by dimasciput** [comment]
@gubuntu currently I use this tag format for releases :
- https://github.com/kartoza/LEDET_BIMS/releases → 0.1
- https://github.com/kartoza/django-bims/releases → 0.2
