### ISSUE TITLE
test local connection

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#289]
# Problem

payment of the next milestone invoice depends on LEDET staff being able to consume OWS services and connect to PostGIS on production

# Solution

Test and confirm _TODAY and up to 25 Sept_ that this is the case. Connect via VPN, ask LEDET staff to test on your behalf, etc. 

## Prerequisites
- users and groups are set up in PostGIS
- port 5432 is exposed and pg_hba.conf and postgresql.conf are properly configured

**Comment by dimasciput** [comment]
@gubuntu you want the postgis to be public ? which database ? django or geonode

**Comment by gubuntu** [comment]
geonode db. pg_hba should only allow connections from within the WAN / VPN

duplicate of #40
