### ISSUE TITLE
GeoNode layers and legends not rendering in BIMS

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#297]

**Comment by gubuntu** [comment]
http://bims.ledet.gov.za

GetMap error e.g. Could not find layer geonode:bioregions

**Comment by NyakudyaA** [comment]
WMS request from was inspector works in the browser independently http://bims.ledet.gov.za/geoserver/wms?request=GetLegendGraphic&format=image/png&width=40&height=40&layer=geonode:bioregions

Everything is working fine now. Restarted geoserver
![screenshot 2018-10-11 at 17 08 31](https://user-images.githubusercontent.com/2510900/46814105-4f007600-cd78-11e8-826b-250876e6f84c.png)

**Comment by gubuntu** [comment]
@NyakudyaA I just hit that link and got    
      Can't obtain the schema for the required layer.
geonode:bioregions layer does not exist.


lots of map layers and legends not working in the map.

**Comment by NyakudyaA** [comment]
@gubuntu everything is working fine. It's just a matter of things timing out because of the connection over vpn.

**Comment by gubuntu** [comment]
But I got the response above very quickly which doesn't indicate a timeout but an error

**Comment by NyakudyaA** [comment]
Can you try it now because I can access all the layers and their legends now.

**Comment by gubuntu** [comment]
<img width="1000" alt="screen shot 2018-10-11 at 21 09 47" src="https://user-images.githubusercontent.com/496911/46827870-0c4f9580-cd9a-11e8-9469-c0359f0a5bb3.png">

**Comment by NyakudyaA** [comment]
@gubuntu here is how they look
![screenshot 2018-10-11 at 21 11 44](https://user-images.githubusercontent.com/2510900/46827992-533d8b00-cd9a-11e8-99cc-1379d1c5491f.png)

**Comment by NyakudyaA** [comment]
and the legends

![screenshot 2018-10-11 at 21 16 39](https://user-images.githubusercontent.com/2510900/46828244-0d34f700-cd9b-11e8-9563-45aa8306095b.png)
![screenshot 2018-10-11 at 21 16 52](https://user-images.githubusercontent.com/2510900/46828245-0d34f700-cd9b-11e8-9114-cc574cb526f8.png)

**Comment by dimasciput** [comment]
@gubuntu try use different browser, maybe it wae cached

**Comment by NyakudyaA** [comment]
Fixed the issue with this. @gubuntu you can test again and close.
