### ISSUE TITLE
WMS not working in production

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#298]
http://bims.ledet.gov.za/geoserver/wms

failed to parse getcapabilities

At least WFS and WCS are working. 

@NyakudyaA can you confirm that OWS access enforces GeoNode permissions?

**Comment by NyakudyaA** [comment]
The get capabilities are working fine. I can access http://bims.ledet.gov.za/geoserver/wms?service=wms&version=1.1.1&request=GetCapabilities
![screenshot 2018-10-11 at 15 42 10](https://user-images.githubusercontent.com/2510900/46808272-41dd8a00-cd6c-11e8-90c1-9d4773dfd6ee.png)

**Comment by NyakudyaA** [comment]
I can get was access was services fine from GeoServer
![screenshot 2018-10-11 at 15 57 22](https://user-images.githubusercontent.com/2510900/46809650-393a8300-cd6f-11e8-9744-27d81e9e6283.png)

![screenshot 2018-10-11 at 15 57 46](https://user-images.githubusercontent.com/2510900/46809665-422b5480-cd6f-11e8-8694-f12e8797cdad.png)

If the layers are public layers then anyone can access them but private layers should require authentication.
