### ISSUE TITLE
cannot connect to PostGIS

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#299]
5432 appears to be open but pg_hba is not configured to allow connectoins from the WAN. 

and probably postgresql.conf is not configured to listen on the right IP. 

These configs need to be built into the production Rancher environment.

**Comment by NyakudyaA** [comment]
I have opened up the port manually. I will leave this ticket open so that @dimasciput can implement directly in rancher
![screenshot 2018-10-15 at 11 36 56](https://user-images.githubusercontent.com/2510900/46943020-f75f5480-d06e-11e8-80a2-3279cb1ab6bf.png)

**Comment by gubuntu** [comment]
@NyakudyaA please specify the exact changes to postgresql.conf and pg_hba.conf to allow WAN access

**Comment by NyakudyaA** [comment]
@dimasciput  I changed the following lines. 

from postgresql.conf I changed
`listen_address= 'localhost'` to `listen_address='*'`

In pg_hba.conf I added the following line

`host  all  all 10.52.82.20/24 md5`

**Comment by NyakudyaA** [comment]
@Vince-Egan is happy with the PostgreSQL connection through QGIS or PgAdmin

**Comment by dimasciput** [comment]
In rancher I just need to set ALLOW_RANGE to 0.0.0.0/0
![screen shot 2018-10-26 at 10 07 46 am](https://user-images.githubusercontent.com/1979569/47542419-7c682a80-d907-11e8-8170-48686570980d.png)

Because now that it works, I'm closing this ticket.

**Comment by gubuntu** [comment]
I'm happy from your side @dimasciput but in production we can't allow connections from any IP so @NyakudyaA please apply that WAN IP Range. 

I'm assuming these override pg_hba settings.

**Comment by NyakudyaA** [comment]
@gubuntu I have specified the ip range in the pg_hba.conf. Do you mean I have to specify that in the `postgresql.conf` as well

**Comment by NyakudyaA** [comment]
@dimasciput  I why do we not just define the IP range using the ALLOW_RANGE because this overrides the pg_hba settings

**Comment by gubuntu** [comment]
'listen addresses' either in postgresql.conf or as an env variable should be set to the IP of the host and not *

Connections should only be allowed from the WAN IP range (10.52.82.20/24) - set in pg_hba or env variable

**Comment by NyakudyaA** [comment]
> 'listen addresses' either in postgresql.conf or as an env variable should be set to the IP of the host and not *
> 
> Connections should only be allowed from the WAN IP range (10.52.82.20/24) - set in pg_hba or env variable

@gubuntu 
The env variable ALLOW_RANGE overrides anything you set manually in the pg_hba.conf which I had already done.
So instead of putting the ALLOW_RANGE as 0.0.0.0/0 it should be `10.52.82.20/24`

So @dimasciput can you change that variable to be that IP range

I will see if Postgres image has a variable for listen address

**Comment by NyakudyaA** [comment]
@dimasciput Next time we do a release we need to have these settings in the database.

```
ALLOW_RANGE=10.0.0.0/8
IP_LIST=10.42.160.23 # We can add other IP address we need to restrict the connections to.
```

**Comment by NyakudyaA** [comment]
@dimasciput have you updated the production instance with the latest Postgres image?

**Comment by NyakudyaA** [comment]
I am closing this as the production instance is working properly now.
![screenshot 2019-01-18 at 17 23 39](https://user-images.githubusercontent.com/2510900/51395596-d6af0b00-1b45-11e9-8863-00d58a88eb7d.png)
