### ISSUE TITLE
FR15 Implement layer filtering

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#30]
filtering should act on

- the active layer (by default the biodiversity layer) AND
       ~~- this means a user must be able to choose which layer is active~~
 - records in the view extent AND
 - the results of a search (if a search was performed)

When a record in a search / filter result is clicked on, zoom to that feature and show its 'report'

Persist search / filter results during and across sessions until a user does another search or filter or clears the search

Starting a search clears a filter but not vice versa

It should be easy to clear both filter and search

child of #31

depends on #169

**Comment by gubuntu** [comment]
filtering should act on

- the active layer (by default the biodiversity layer) AND
  - this means a user must be able to choose which layer is active
- records in the view extent AND
- the results of a search (if a search was performed)

When a record  in a search / filter result is clicked on, zoom to that feature and show its 'report' 

Persist search / filter results during and across sessions until a user does another search or filter or clears the search

Starting a search clears a filter but not vice versa

It should be easy to clear both filter and search

**Comment by gubuntu** [comment]
from demo July 5:
> Filters need to be contextual w.r.t. Search and view-frame.

**Comment by Vries14** [comment]
- filtering acts on records, active layers and search results.
- When clicking on cluster, zooms to record, shows info when click on green cluster.
- Search results persists during session.
- Able to clear search and filter results easily with "reset button"
