### ISSUE TITLE
Flatpages does not work

### ISSUE THREAD

**Issue by anitanh** [kartoza/LEDET_BIMS#302]
# Problem
I tried to add a new flatpage page in the admin but I got template does not exist in debug mode.

# Solution
Fix it

Related to https://github.com/kartoza/LEDET_BIMS/issues/160

**Comment by dimasciput** [comment]
Error occurred here : https://testing.limpopobims.kartoza.com/admin/flatpages/flatpage/add/

**Comment by Vries14** [comment]
Able to add flatpages.
