### ISSUE TITLE
Print basic map

### ISSUE THREAD

**Issue by anitanh** [kartoza/LEDET_BIMS#303]
We should be able to print the basic map with layers that has been chosen by the user and the legend.

child of #67

**Comment by Vries14** [comment]
There still a problem:  when I tried to print a small portion of the map I was able to download it (this is the map that printed):
![map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46e5958a61cec1b99de6b546a749b2ce6b1326722d55f27d72d3b52cbc172a515f5e1ca9150b5b47f9eb9539e4e76224d50152a7842f4d7ed43c18a6b9871bbb00bd24834786b3bf8f5e8d.png)

When I tried a larger view I got the `failed-network error` message(This is the view I tried to print):
![Screenshot from 2018-12-07 11-29-41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f2793dd5b468ee13365356424aad53444d04bea6d37ef5f22e7a98595abc856c5e72943b17f8eb871ebf01bb728e1bd6b2bf8f5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5cf24ae64855a11a3f64ee647b.png)

**Comment by dimasciput** [comment]
@Vries14 can you try it again?

**Comment by Vries14** [comment]
Im now able to print the maps
