### ISSUE TITLE
Can't reset password on oauth account

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#309]
Is it by design that one cannot set a password on an account that was created via OAuth?

(on staging)

**Comment by dimasciput** [comment]
Yes you can, first you need to go to profile page 

![image](https://user-images.githubusercontent.com/1979569/51579965-79c0a580-1ef5-11e9-8674-22981d108e3a.png)

Then click the set/change password.
![image](https://user-images.githubusercontent.com/1979569/51581126-70393c80-1ef9-11e9-8c71-c7815f6866f0.png)
