### ISSUE TITLE
slow response on clicking 'Edit data' in validation panel

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#318]
on testing.limpopobims I click edit and nothing happens for a few seconds. 

Is it a very slow process?

If the user has to wait then make it modal with a spinner or something so the user doesn't do anything else until there is a response

**Comment by dimasciput** [comment]
@gubuntu please try again, testing was very slow because I tried enabling the geondoe monitoring yesterday.

**Comment by gubuntu** [comment]
fractionally faster now. 

Does monitoring add such a large overhead?
