### ISSUE TITLE
staging is broken

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#326]
https://staging.limpopobims.kartoza.com/map/

on firefox, done many hard refreshes...
![Screenshot 2019-01-27 at 10.41.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7b53e32a64c5b278f1162a4f5d5e5cb053181d1ba6acda6fb4bc2e75db0d5fecd06b0d72c06942a9b9821fbe53bf74d84b86b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc05df143e74d53a0113571ab.png)

**Comment by NyakudyaA** [comment]
@gubuntu Is it not working for other browsers too. 
I have just tested it on my firefox and it works.

![screenshot 2019-01-27 at 10 59 20](https://user-images.githubusercontent.com/2510900/51798923-eb189500-2222-11e9-9971-63e7e52e7cb5.png)

**Comment by gubuntu** [comment]
I can see the map in Chrome without logging in. But when I log in as kartoza_admin it breaks. 

In any case, everything should be browser independent and no user should ever encounter issues like this (except maybe after an upgrade when you might need to do one hard refresh)

**Comment by dimasciput** [comment]
please test again

**Comment by NyakudyaA** [comment]
@dimasciput staging is still broken. I tried to get access it and even restarted nginx from rancher and still no access. Tried on both chrome and firefox

![staging](https://user-images.githubusercontent.com/2510900/53878364-5a4c8a80-4014-11e9-9447-228a7b12dfcf.png)

**Comment by NyakudyaA** [comment]
Been working for a couple of days now.
