### ISSUE TITLE
identify not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#327]
doesn't seem to be working at all on testing

for a while on production I could click in the map and get a response for one layer. 

Then I added another layer and from then on, got no response. 

Sometimes it works, but really slowly. 

Also, the popup does not move the map or place itself to fit properly, especially if large. 

Please check and fix

Also please explain intended behaviour - should it drill down through all layers that are switched on? Or is there the concept of an 'active layer' where it just queries the active layer?

**Comment by gubuntu** [comment]
maybe a clue: at one point ages after clicking on the map I click download. When the downnload dialog opened, the identify popup also opened. May have been coincidence but maybe not

**Comment by dimasciput** [comment]
> Also please explain intended behaviour - should it drill down through all layers that are switched on? Or is there the concept of an 'active layer' where it just queries the active layer?

@gubuntu it will just queries the active layers

**Comment by gubuntu** [comment]
what is an active layer? one that is switched on i.e. rendering?

**Comment by dimasciput** [comment]
switched on from the layer selector
