### ISSUE TITLE
panels not populating

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#329]
# problem

on production and testing

neither the site nor taxon panels are populating  - they just say (loading)

# solution

investigate and fix

**Comment by dimasciput** [comment]
Testing is working as intended, haven't checked production

**Comment by dimasciput** [comment]
production also populating

**Comment by gubuntu** [comment]
please add a screencast, it didn't work for @Vince-Egan nor me on production yesterday
