### ISSUE TITLE
Layer permisions not applied correctly

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#340]
# Problem
There is something wrong with the permissions of layers and groups

* Public layers should be accessible by anonymous users without logging in
![pub](https://user-images.githubusercontent.com/2510900/53723100-a3afa500-3e6f-11e9-9093-641bc374a1f4.png)

Trying to view a public layer results in the following

![public](https://user-images.githubusercontent.com/2510900/53723105-a8745900-3e6f-11e9-8f2c-c05870f44ee0.png)

* Private layers should not be visible to anonymous layers
![layers](https://user-images.githubusercontent.com/2510900/53723140-bb872900-3e6f-11e9-89b6-a96597f55ceb.png)

# Solution
Investigate and fix

**Comment by NyakudyaA** [comment]
The  cause of this is geofence rules are not being updated at all from Geonode on testing. I can't test on staging because it's broken and production seems unreachable

**Comment by gubuntu** [comment]
@NyakudyaA is the geofence issue the same one we had on ST? Pls log it as a GeoNode issue if it's an upstream issue or ask about it on GeoNode gitter or list. 

It's critical that everything's working on staging and production well before the launch on Friday cc @dimasciput

**Comment by NyakudyaA** [comment]
It's not a Geonode issue, there is something from our side that broke it . On ST I had to use a new data directory for Geoserver and it worked

**Comment by NyakudyaA** [comment]
This works well in staging and testing
