### ISSUE TITLE
FR33 Implement minimal document management functionality

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#37]
user GeoNode document management?

Link a document to a site

treat photographs separately (i.e. render rather than link)

child of #71

**Comment by timlinux** [comment]
For documents we should use geonode documents ideally. If we need to link a document to a site (or record) or photo to site or record, we should extend the site and bilogicalcollection models to accommodate that.

**Comment by timlinux** [comment]
For a full blown document management system, there is Mayan: https://github.com/tell-k/django-modelsdoc - maybe a bit overkill for us though?

**Comment by timlinux** [comment]
BTW Mayan is docker ready.

**Comment by gubuntu** [comment]
from demo July 5:
> All uploaded documents must be referenced in the bibliography, with a hyperlink to the document.

i.e. records in the bibliography can include links to remote or local documents. Conversely, all local documents must be described and linked to by a record in the bibliography

Implication: bibliography must be indexed for search. 

So @carina1000 the UI for documents and bibliography should be merged or at leasted designed carefully.

**Comment by carina1000** [comment]
@gubuntu will the list of documents in the bibliography page look similar to this perhaps? (mock up for Documents & Reports #71)
![Screen Shot 2018-07-31 at 12.53.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246457f26b7191a379ed0c2e52415c49be5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecb5bf648e54953ac1b3364f43b.png)

**Comment by gubuntu** [comment]
see https://github.com/kartoza/LEDET_BIMS/issues/210#issuecomment-409205915

**Comment by dimasciput** [comment]
Resolved using geonode documents and changed the layout, also added taxon links when users add or edit document.

**Comment by Vries14** [comment]
Documents linked to taxon records. when  searching for taxa and when editing records or documents
