### ISSUE TITLE
FR34 Enable data categorisation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#38]
Each layer should be tagged with at least one of these standard keywords, presented in the links below. 

At the very least these should be in the appropriate metadata element but we can consider filing data sets in folders or schemas with the same names as well. 

https://geo-ide.noaa.gov/wiki/index.php?title=ISO_Topic_Categories

http://gisgate.co.clark.nv.us/gismo/keywords.htm

**Comment by gubuntu** [comment]
@NyakudyaA what is there to review. Otherwise please move into more appropriate column

**Comment by NyakudyaA** [comment]
I will close this as all layers have good metadata with categories
![cat](https://user-images.githubusercontent.com/2510900/43569603-3dd7c2ba-9638-11e8-811d-d50ad54350de.png)
