### ISSUE TITLE
FR48 publish these layers

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#39]
- [ ] transformation
   - land cover transformation?
- [ ] plant communities
- [x] vegetation
    - SANBI vegetation types (Mucina & Rutherford)
- [x] rivers
    - source? scale?
- [x] All NFEPA layers
- [x] roads
    - source, scale?
- [x] towns
    - source, scale?
- [ ] townships
    - definition? source, scale?
- [x] districts
    - MDB
- [x] local municipalities
    - MDB
- [x] provincial boundary
    - MDB?
- [x] EMFs
    - Environmental Management Framework? LEDET?
  - style highlight sensitive areas
- [x] biospheres
    - SANBI? LEDET?
  - + core areas
- [x] Biomes
   - SANBI? LEDET?
- [x] 50m contours 
   - surely 20m? NGI
- [ ] LEDET service centres and offices
   - LEDET
  - A ‘Service Centre’ content type is required with fields for Service Centre Name, Service centre location (geospatial point locations), and service centre areas of operation (geospatial polygons). This should be related back to the district layer to allow for reporting per district. An interface is required for the updating of this information.
- [x] farm boundaries
    - raw SG data?
- [x] farm portions
     - raw SG data?
- [ ] A content type linking to the farm boundaries and farm portions cadastres should be created to capture P3 Exemption properties via a Boolean Yes/No field. An additional field should also be created to capture the species to which the exemption relates – this will require the capture of a number of species against each property.
- [x] erven
- [ ] threatened and protected ecosystems (themed by original extent and remaining extent)
    - DEA? LEDET?
- [ ] divisions
    - ?
- [ ] protected areas (themed by status)
    - DEA? LEDET?
    - also generate buffer layer or style dynamically - 5km provincial, 10km national and WHS
- [x] river ecoregions
    - LEDET
- [x] wetlands
    - LEDET? DEA?
- [x] dams
    - DWS? others?
- [ ] development pressure
    - LEDET
- [x] secondary catchment
    - DWS
- [x] tertiary catchment
    - DWS
- [x] quaternary catchment
    - DWS
- [ ] pentad grid
    - clarify (1:10000 grid?)
- [ ] QDS grid
    - 1:50000 toposheet grid
- [ ]  Limpopo conservation plan
    - LEDET
- [ ] bioregional plans (themed by status – proposed/approved)
    - LEDET
- [ ] ecosystems
     - LEDET
- [ ] biodiversity management plans
    - LEDET
- [ ] satellite images
    - LEDET
- [ ] aerial photographs
    - LEDET
- [x] NPAES (National Protected Area Expansion Areas)
    - plus 'focus areas'
- [x] LPAES (Limpopo Protected Area Expansion Areas)
- [ ] Mining
- [ ]  Prospecting rights
- [ ]  Homelands
- [ ]  council areas
- [x]  Schools
- [ ]  Invasive species data
- [ ] Freshwater Ecosystem Priority Areas
- [ ] Land-claims (coded to show status of claims)
- [x] World Heritage Sites
- [ ] Sites or areas identified in terms of international conventions
- [ ] Conservation areas i.t.o. SDF (Provincial SDF developed)
- [ ] Areas zoned for use as public open space
- [ ] A ‘Wildlife Activities’ content type should be created to allow for the capture of intensive game breeding operations, breeding centres, rehabilitation centres, etc. This should include the name of the facility, the type of facility, point location (geospatial point locations), area location (geospatial polygons), and the species that are maintained at the facility (this will require a drop-down menu link to the taxon field, with a one-to-many relationship).
- [ ] Distribution data for the following free-roaming taxa:
  - Cheetah
  - Elephant
  - Roan antelope
  - Crocodiles
  - Black rhino
  - White rhino
- [ ] Impoundments – dams & weirs.
- [ ] Permit applications import from WTR database (out of scope)
- [ ] Habitat suitability per species.
- [ ] There is a need for a ‘IPWM Activity’ content type with the following fields: Facility Name, Facility Type, Facility point location (geospatial point locations), Facility area location (polygon), licensing, closest river and discharge point (geospatial point location; this should be optional). A field should also be included to relate the data to districts and local municipalities. Spatial data captured within this content type will be retrieved per content type (e.g. Effluent/treatment facilities, landfills, etc.)
  - Landfill site locations (see General requirements)
  - Pollution-generating facilities
  - Effluent /treatment facility locations (see General Requirements)
  - Effluent /treatment facility discharge points
  - Ambient air quality monitoring stations.
- [x] wards
- [ ] cluster boundaries (Polokwane munic)?
- [ ] traditional authority boundaries
- [ ] industrial areas (i.e. zoning)
- [ ] flood lines
- [ ] servitudes
- [x] groundwater
  - incl aquifers
- [ ] urban edge
- [ ] ridges (topographical features)
- [ ] agricultural potential
- [x] geology
  - incl dolomite
- [ ] soil types

**Comment by NyakudyaA** [comment]
For roads, we could add the [docker-osm](https://github.com/kartoza/docker-osm) into the integration and get the latest roads daily.

**Comment by Vince-Egan** [comment]
@NyakudyaA : I have uploaded a tab-delimited file with reptile data BIMS_to_kartoza_2018-06-01.txt to my Dropbox account.
Also the following shapefiles:
LIMP_BiosphereReserves - Biosphere boundaries, from our Protected Area Expansion Strategy
LIMP_PA_April2014 - Protected Areas, from the Protected Area Expansion Strategy
LIMP_Towns - towns, again from the expansion strategy
LPAES_FocusAreas - from the expansion strategy
LPAES_Focus regions - from the expansion strategy

**Comment by NyakudyaA** [comment]
thanks @Vince-Egan will download them now

**Comment by NyakudyaA** [comment]
Hi @Vince-Egan can you please comment on the availability of layers that have been tagged `LEDET` in the list

**Comment by gubuntu** [comment]
@NyakudyaA please work on layers styles and labels and basic metadata for the demo - especially for the layers that are in the staging map.

**Comment by gubuntu** [comment]
@NyakudyaA please publish pollution and waste layers that @Vince-Egan just added to DropBox

**Comment by NyakudyaA** [comment]
@gubuntu some of the styles for the layers I have just inherited them from the custodians of the data where I downloaded them.

**Comment by gubuntu** [comment]
@NyakudyaA if you inherit styles with layers then leave them. I'm referring to layers that came with no published styles or layers that have official styles (like vegmap) that have not been applied.

**Comment by NyakudyaA** [comment]
Hi @Vince-Egan any update on the layers referenced as Ledet from this ticket

**Comment by gubuntu** [comment]
All available and supplied layers have been loaded, styled and published in the GeoNode component of the system. Outstanding layers can be maintained by LEDET staff after delivery and training. I'm happy that this, along with #64 satisfies FR48
