### ISSUE TITLE
FR38 set up folders, schemas and permissions for GIS users and admins

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#41]
> The LBIMS shall allow only GIS users and a GIS administrator to access and store data in the back-end through a desktop client. They will keep staging / temporary data on their own computer or in a server home directory or database ‘home schema’ and then publish the layers in a web map server and the LBIMS UI.

**Comment by NyakudyaA** [comment]
I have added a schema in the database called `data` that will be used for temporary storage of data.  
**Roles**
* `editor` - For users uploading data into the database, editing, styling 
* `admin` - Complete access to all schemas

**Schemas**
* Public - Geonode reads this by default
* data - temporary store for use by editors
![database_users.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46e77953d2fd0f723be9/125516c66e82c728ace21e0d46ec958e228082ba8ad6aa50a14fe3d665043761260ea62864c7b96aea437a055e5e48fe475e0b17f9f8892ba7e43924d95808e8c3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc2ec3e20ef8f884636191755.png)

For folder access on the LAN, I will wait for access

**Comment by NyakudyaA** [comment]
@gubuntu  I have created the roles as defined in the permission matrix. We have the following roles

A user can belong to the roles defined in the matrix either as admin or editor for that group.
**Example**
`Protected Area Management  role can either be RO or RW for a specific user.`

**Comment by gubuntu** [comment]
@NyakudyaA please explain more complehensively as documentation in the tech doc.

**Comment by NyakudyaA** [comment]
@gubuntu the permission matrix already defines this. It says a Protected admin user has access to a certain number of layers. I added the following roles
![screenshot 2018-10-25 at 11 42 50](https://user-images.githubusercontent.com/2510900/47491465-2c2b9280-d84b-11e8-860e-12c797fc5ed9.png)

`pam_editor` any user assigned to this role will only have read access to the layers defined in the Matrix

`pam_admin` any user assigned this role will have rad write access to the layers mentioned in the permission matrix.

Currently PAM role should have access to the following layers
```
towns
ledet offices
farm boundaries
farm subdivision
protected areas
protected areas buffer
National Protected Area Expansion Strategy (NPAES) (poly)
Limpopo Protected Area Expansion Strategy (LPAES) (poly)
Land Claims (themed by status)(poly)
```

**Comment by NyakudyaA** [comment]
This has been achieved and will close the OP.

![screenshot 2019-01-18 at 15 46 34](https://user-images.githubusercontent.com/2510900/51390575-5d5ceb80-1b38-11e9-889f-278dbcf64b1b.png)

![screenshot 2019-01-18 at 15 46 11](https://user-images.githubusercontent.com/2510900/51390577-5df58200-1b38-11e9-8487-cb6505a15fb4.png)

**Comment by gubuntu** [comment]
thanks, add to manual please @NyakudyaA
