### ISSUE TITLE
FR39 develop and document GIS publishing workflow

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#42]
e.g.

1. GIS user preps data and QGIS and SLD styles and submits to GIS admin for publication
1. GIS admin loads into final schema or folder
1. GIS admin applies final style and saves as default in database
1. GIS admin publishes in Geoserver and applies SLD and permissions

> The LBIMS shall allow a GIS user to submit working files for publishing and provide a metadata capture interface on the UI. 

> GIS users submit working files once they are complete, the data can then be published on the LBIMS by an admin user who has approved the data.

**Comment by NyakudyaA** [comment]
@gubuntu I have created a doc in my drive. Where can I move it to so that it is in one central place with other docs

**Comment by gubuntu** [comment]
https://drive.google.com/open?id=1p5vd3SPtSQBvXYphK-JMPqN73xqpsWhb

**Comment by NyakudyaA** [comment]
@gubuntu  I cannot move the file. The folder has read-only permission

**Comment by gubuntu** [comment]
please try again

**Comment by NyakudyaA** [comment]
@gubuntu  I have moved it

**Comment by gubuntu** [comment]
I'm reviewing and editing
