### ISSUE TITLE
FR43 FR24 implement content and usage monitoring dashboard

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#45]
> The LBIMS shall provide administrative users with a UI to monitor and report on a number of functions such as: logins per user group over time, the number of taxon records on the database and the number of users per user role, summary data of all functions should be exportable in spreadsheet, word, plain text and pdf formats.

email regular reports to admin users and TSC and PSC members (should be configurable in monitoring tool)

**Comment by dimasciput** [comment]
@ann26 
Next todo:

- [x] Email regular reports to admin users

**Comment by Vries14** [comment]
usage monitoring dashboard implemented
