### ISSUE TITLE
FR50 FR51 protected area admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#48]
in addition to the GIS admin user(s) who have full rights on all folders, schemas and Geoserver, there needs to be a protected area admin user.

furthermore:
> The LBIMS shall enable protected areas users to manage content on declaration status, management authority and land-owner contact details for a particular location from the UI. 

clarificaton required @Vince-Egan : assuming this means the GIS or DB UI, but it could mean the web UI? In which case it must be managed via BIMS Django and implemented through WFS-T

related to #51
depends on https://github.com/kartoza/django-bims/issues/74

**Comment by Vince-Egan** [comment]
@gubuntu @timlinux We need to have a GIS user to manage Protected Area data too (in addition to the Biodiversity Management personnel who will be managing Biodiversity tables).
I don't know enough to comment on Tim's suggestion...

**Comment by gubuntu** [comment]
If it's just a GIS user then their role will easily be managed like the other GIS users - either through database roles or corporate single sign on. 

So we'd need to know who that is at some point and which specific datasets they need to manage.

**Comment by NyakudyaA** [comment]
@gubuntu Can you please clarify this for me. 
Besides the permissions assigned to the Protected Area Management in Geonode that allows the users belonging to this group to manage  resources with these permissions we need to create roles in the database for users to manage these datasets.

I would assume we need to  create a role protected_area_management in the database and then grant select,update,delete and insert for these layers ?

**Comment by gubuntu** [comment]
yes that sounds right @NyakudyaA 

please apply in production and also document in a permission matrix sheet, perhaps by extending the existing permission matrix google sheet

**Comment by NyakudyaA** [comment]
I have added these in the permission matrix sheet. Now awaiting access to the production to implement this

**Comment by NyakudyaA** [comment]
I have created all the roles in the database as specified in the permission matrix
![screenshot 2018-10-23 at 16 30 08](https://user-images.githubusercontent.com/2510900/47367914-f1a5e680-d6e0-11e8-847a-fb5384e3bc76.png)

These roles can either be `RO or RW`

**Comment by gubuntu** [comment]
@NyakudyaA pls describe specifically how the proteced area admin is set up as per OP

**Comment by NyakudyaA** [comment]
@gubuntu this has been implemented in the database as `pam_editor` who has got RO permissions.
`pam_admin` has been set up in the DB with RW permissions.

So suppose we have a layer called `Bioversity` in the database and the same layer is published in Geonode.

In Geonode `PAM` group will have access to this layer.
In the DB a user can either be `pam_editor` or `pam_admin`

**Comment by NyakudyaA** [comment]
This is now implemented and working for all PAM users.

![screenshot 2019-01-18 at 15 46 34](https://user-images.githubusercontent.com/2510900/51390717-b7f64780-1b38-11e9-95e5-8d6fbb911b96.png)

![screenshot 2019-01-18 at 15 46 11](https://user-images.githubusercontent.com/2510900/51390718-b7f64780-1b38-11e9-9298-6f10e621ebb4.png)

**Comment by gubuntu** [comment]
thanks @NyakudyaA please add the explanations and screenshots (for this and other relevant issues) to the appropriate manual - in this case the GIS user manual
