### ISSUE TITLE
FR52 Implement role-based context for protected areas users

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#49]

**Comment by NyakudyaA** [comment]
This is possible based on the permissions assigned to users.
A user being part of the protected areas
![screen shot 2018-09-18 at 09 56 12](https://user-images.githubusercontent.com/2510900/45674468-7bd0bd00-bb2d-11e8-8d79-c2dd7d96c224.png)

Layers visible in Geonode
![screen shot 2018-09-18 at 10 26 23](https://user-images.githubusercontent.com/2510900/45674504-90ad5080-bb2d-11e8-9427-c6cef3e3f20a.png)

In the bims app we can only see this layer
![screen shot 2018-09-18 at 10 35 34](https://user-images.githubusercontent.com/2510900/45675066-b38c3480-bb2e-11e8-8945-9c3c6d1878cf.png)

**Comment by NyakudyaA** [comment]
This is possible based on the permissions assigned to users.
A user being part of the protected areas
![screen shot 2018-09-18 at 09 56 12](https://user-images.githubusercontent.com/2510900/45674468-7bd0bd00-bb2d-11e8-8d79-c2dd7d96c224.png)

Layers visible in Geonode
![screen shot 2018-09-18 at 10 26 23](https://user-images.githubusercontent.com/2510900/45674504-90ad5080-bb2d-11e8-9427-c6cef3e3f20a.png)
