### ISSUE TITLE
FR56 add a links page, managed through admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#53]
Add a flat page or rich content CMS page that can be managed through BIMS Django admin, to list links with some contextual information

view privileges allocated per role.

See #68 for roles

**Comment by timlinux** [comment]
@sonlinux before using flatpages, please look and see if there is an off the shelf django app we can use here. e.g.

https://github.com/kplaube/django-simple-links

That should be included in k-bims core. There should be a link to it from the menu bar.

**Comment by Vince-Egan** [comment]
@gubuntu: This would simply link to external web pages. If we can sort them by a category/tag, that would be great.

**Comment by timlinux** [comment]
@Vince-Egan yes I think the proposed simple links app will be fine for that - @sonlinux make sure to add sortable behaviour by category.

```
{% load link_list %}

{% get_link_list "blogroll" as links, category %}

{% if links %}
    <div class="module">
        <h3 class="title">{{ category.title }}</h3>
        <ul>
            {% for link in links %}
                <li>
                    <a href="{{ link.href }}"
                        title="{{ link.description }}">{{ link.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
```
