### ISSUE TITLE
NFR1 provide technical and design documentation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#54]

**Comment by timlinux** [comment]
@dimasciput we can deploy this:

https://github.com/tell-k/django-modelsdoc

And make sure all devs document their models clearly. Then we will get automatic document generation.

**Comment by dimasciput** [comment]
Hi @sonlinux , have you started this yet?

**Comment by sonlinux** [comment]
Am working on it today @dimasciput

**Comment by gubuntu** [comment]
opening again, this work should have been against another ticket for code documentation?

The title of this issue (and the ref in the Google Doc) has not been done yet...
