### ISSUE TITLE
FR10 FR33 FR45 FR49 Upload distribution data from Excel

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#6]
this refers to standard biodiversity observation data ('distribution' refers to the location as xy point coordinates or polygon) i.e. the generic biodiversity record class. 

In this ticket, handle upload from Excel (other tickets handle upload from csv, shapefile and other formats). also see the requirements document for further context.

**Comment by dimasciput** [comment]
@gubuntu Any example of the distribution data?

**Comment by cchristelis** [comment]
@ann26, if this takes more than 1/4 day, please move this back to backlog.

**Comment by gubuntu** [comment]
I'm moving it back to the backlog. Excel is not actually specified, if anything it should be ods (MIOS compliant). For now csv and shapfile are fine and they have both been implemented already
