### ISSUE TITLE
FR53 publish EIA data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#60]
> The LBIMS shall incorporate the EIA database of spatial distribution records in vector format to allow users to perform data analysis from the UI.

This is not clear. Can we assume this is one layer representing EIA applications / projects - please expand @Vince-Egan?

**Comment by gubuntu** [comment]
@Vince-Egan please explain:
> Please make this dependent on LEDET providing the required linkages, etc.

**Comment by Vince-Egan** [comment]
@gubuntu: 
We will have access to two datasets for EIAs themselves (an SRK dataset with point data and a polygon dataset that we are currently capturing). Attribute data can be collapsed into a single table, but there will be 2 geometries that apply to the records.
The other EIA data is the taxon distribution data that is captured in the EIAs - my comment (Please make this dependent on LEDET providing the required linkages, etc.) assumed you meant this. This data should form part of the main taxon distribution dataset though so we should probably disregard it as a specific requirement.

**Comment by gubuntu** [comment]
@Vince-Egan the point data are incomplete in dropbox (there is only a cpg file) and I'm struggling to open the gdb - Is is a normal ESRI file geodatabase?

**Comment by Vince-Egan** [comment]
@gubuntu : I have updated the files on dropbox - both are now in shapefile format.

**Comment by gubuntu** [comment]
@NyakudyaA I have uploaded these into GeoNode. 
- Developments_EIA-polygons
- Developments_EIA-points

It's weird that I can login and even upload a layer but I still can't authenticate to Geoserver nor can I edit styles through GeoNode. The point style I created didn't go through so I'll send it via Slack - please apply it. 

@Vince-Egan I've left the fields as is but I imagine these are internal layers you will want to maintain? Your team can clean up the fields and get the geometries to share attributes - something to try in training.

**Comment by NyakudyaA** [comment]
@gubuntu  the reason why you could not edit the style was that it was not a valid style hence giving an error.
```
QgsMarkerSymbolLayer FilledMarker not implemented yet-->
```

**Comment by gubuntu** [comment]
https://testing.limpopobims.kartoza.com/layers/geonode:srk_point_data_eia

https://testing.limpopobims.kartoza.com/layers/geonode:developments
