### ISSUE TITLE
FR58 Create end-user groups

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#63]
LBIMS end-users shall be allocated to one or more of the following end-user groups
- internal users (LEDET directorates - each of these should be a group or sub group)
  - Biodiversity Management
  - Protected Area Management
  - Environmental Research & Planning
  - Environmental Impact Management
  - Wildlife Trade & Regulation
  - Integrated Pollution & Waste
- the South African National Biodiversity Institute (SANBI)
- Local Government
  - Polokwane Municipality (the pilot)
- Environmental Assessment Practitioners.

These must be applicable across all system components (BIMS, PostGIS, GeoNode)

child of #4

**Comment by dimasciput** [comment]
Right now I added them as a group

![screen shot 2018-06-06 at 4 07 47 pm](https://user-images.githubusercontent.com/1979569/41028980-c277d1f6-69a4-11e8-9209-74b45ee73cfb.png)

**Comment by dimasciput** [comment]
this will be added from geonode manually

**Comment by gubuntu** [comment]
@NyakudyaA please test a couple of these (all testing on the testing server, not staging)

@dimasciput should we wait for production deployment before adding the full list of final groups? If so, that's even more reason to get that production instance deployed ASAP.

**Comment by gubuntu** [comment]
I see these groups exist on testing and staging
