### ISSUE TITLE
FR48 species occurrence on map and via search

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#64]
Taxon / species occurrence. This is the core biodiversity data. i.e. will be managed by BIMS component, not GIS.
- include red list species (species by CITES)

child of #31

**Comment by timlinux** [comment]
@meomancer we should be using clusters for the onscreen display.

I think we should have extra elements in the json struct of the cluster model listing the number of records per IUCS category (endangered, rare etc.)

@ann26 the search results on the map - maybe we must look at using filtered WMS - speak to  @NyakudyaA about this.

**Comment by Vince-Egan** [comment]
@gubuntu: note that the CITES listing and IUCN conservation status (red listing) are two separate things. The former relates only to international trade.

**Comment by gubuntu** [comment]
I'm happy that the OP is satisfied and that FR48 is partly satisfied
