### ISSUE TITLE
add these base layer options to the map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#65]
- [x] OSM mapsurfer roads (default)
- [x] Dark Matter
- [x] Positron
- [ ] topostyle http://maps.kartoza.com/web/?map=/web/Topostyle/ngi.qgs [experimental] 
- [x] toposheets https://htonl.dev.openstreetmap.org/ngi-tiles/tiles/50k/{z}/{x}/{-y}.png
- [x] Klokantech Terrain
- [x] NGI OSM aerial photographs
- [x] Bing Hybrid

should be configurable through Admin (layers + order + default)

**Comment by Vince-Egan** [comment]
@gubuntu: I don't think we'd need anything more than this, Gavin. Topostyle should keep most end users happy.

**Comment by gubuntu** [comment]
@meomancer please get the final list to match the OP exactly.

**Comment by dimasciput** [comment]
@meomancer can you add the remaining layer ?

**Comment by gubuntu** [comment]
ping @meomancer (and change default to it - Mapsurfer)

**Comment by gubuntu** [comment]
ping @meomancer just a small thing to close this
