### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#71]
Links
- List of links to electronic resources, sorted by resource category and filtered by role viewing permissions.

see #68 for roles

**Comment by timlinux** [comment]
same as #53 ?

**Comment by gubuntu** [comment]
no, #53 is for links, this is for local resources (like documents). Can you help expand this and #53 @Vince-Egan?

**Comment by Vince-Egan** [comment]
@gubuntu: This will be for documents mainly, but could include other files. All files here would be LEDET owned or we'd have permission to host. The resource categories should include 'documents', 'images', 'videos', 'audio files'. Could we have sub-categories of documents 'legislation', 'reports', 'publications', etc.?

**Comment by Vince-Egan** [comment]
Sorry - an errant click!

**Comment by carina1000** [comment]
Please see suggested designs:
![Documents__Reports.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cc9b99368f86a79bfa807c9658e09b3b5234316546b3397f8fe62bab0021435a0e1ff840595916faffdd78a3b73c708b0e0eb982695c71d42103eee9dc4be05ce36ade0d97bcae8b44cae93826e48b8c4b3f1606188af84f78.png)
![Documents__Reports_1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46cc9b99368f86a79bfa807c9658e09b3b52344c7846ef696097ec22ba416f43554d4bfd100c5e45faab8f2df2e539718a5c0abfd4390c70c53803b0aac04ee155e57dd205d0f4ae805ec2e83724e2888c4f3d1a041188f75e33b2d4.png)

**Comment by carina1000** [comment]
Once approved @dimasciput please hand this over to relevant developer

**Comment by carina1000** [comment]
Should we keep the name of this page as "Documents & Reports" as originally designed or should we rename it to "Resources"?

**Comment by gubuntu** [comment]
Bibliography, resources (links), documents, reports should all be together for a user

Each might have its own interface for being managed by an admin. 
- bibliography has the bibliography app admin elements
- links has the links admin page
- reports / docs / photos has the GeoNode document system

**Comment by dimasciput** [comment]
Should we just use documents functionality from geonode for now?

**Comment by gubuntu** [comment]
yes, then we can extend it to do the rest later

**Comment by Vries14** [comment]
- Documents linked to taxon and collection records.
- Able to add documents when editing record.
- Upload docs, link to taxon records
- Documents in side panel linked to taxa
