### ISSUE TITLE
Spatial information (map) page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#72]
# Links
- ‘Locate by coordinates’ link to locate by coordinates interface (pop-up?)
- ‘Locate by farm code’[tool-tip: “Search by Farm or farm portion ID”] link to ‘Search by Farm/Farm Portion Page’
- ‘Navigate on map’ link to Map Navigation Page

## Locate by Coordinates
Information:
Please enter the decimal latitude (positive degrees South) and longitude (positive degrees East) coordinates of your area of interest below?

Fields:
- Latitude (°S) [decimal, with 6 decimal places]
- Longitude (°E) [decimal, with 6 decimal places]

Activities
- ‘Submit’button -> when pressed, links to Map Navigation Page with default zoom set to 1:50000, centred on the entered coordinates.

## Locate by Farm/Farm Portion Code Page
Information:
‘Please enter the Farm/Farm Portion ID below (e.g. T0KT00000000001600005) ’
Fields:
- Farm/Farm Portion ID

Activities
- ‘Submit’button -> search for Farm /Farm Portion ID (2 files to be searched!) and open Map Navigation Page centred on centroid of selected farm.
- ‘Submit’button -> search for Farm /Farm Portion ID (2 files to be searched!): if search criterion not found, open error interface with options to return to ‘Locate by Farm/Farm Portion’ Page or ‘Spatial Information’Page.

## Map Navigation Page
Information:
- Web map interface centred on Limpopo Provincial extent, zoomed to full province by default – if navigated to from ‘Locate by Coordinates’or ‘Locate by Farm/Farm Portion ID’, use zoom level and focus point as per referring page.

Actions:
- Base-maps per role, selected by radio-buttons: see link in #68 pages 4 and 5 and #65
- Overlays per role: see link in #68 pages 4 and 5 and #48
- Navigation by keyboard direction arrows, on-screen arrows and mouse
- Zooming by mouse scroll-wheel or on-screen widget
- ‘Print’ button to print visible map with degree grid, legend and north arrow.

see #68 for roles

**Comment by timlinux** [comment]
In HR we also are adding gazeeteer based / place name based search.

I propose for the farm search we maintain a table of farm centroids and their farm ID in BIMS and then for map display get the farm boundaries from an external WMS service. Admire can you start by getting the Farm Centroids and numbers layers (I think we should have farm no, portion and the full SG code).

**Comment by timlinux** [comment]
@dimasciput can you do the map widgets for this?

**Comment by gubuntu** [comment]
Can we as far as possible blend these requirements with healthyrivers / django-bims and the existing moqups?

I think the only Limpopo-specific functionalities here are the default map view, the specific layers to be made available and the specific role-based access.

**Comment by timlinux** [comment]
We should also provide permalinks for maps so they can be easily shared.

**Comment by gubuntu** [comment]
scope creep :-) (unless dead simple)
