### ISSUE TITLE
FR4 Upload species page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#74]
Facility provided to upload data for all of the following tables with unique key corresponding to those used by SANBI:
- Taxon
- Taxon distribution
- Kingdom
- Phylum
- Class
- Order
- Family
- CITES listing
- IUCN Status
- Nature Reserves
- Province
- District Municipality
- Local Municipality
- Record Type
- Locality Method

see #68 for roles

**Comment by cchristelis** [comment]
This goes back to the whole implicit vs explicit data. We shouldn't burden the user with giving information (such as Province) which we can easily look up implicitly...

**Comment by timlinux** [comment]
We need to add a generic biologicalcollection form similar to fish uploader.
