### ISSUE TITLE
Taxon evaluation page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#75]
(Access allocated at user level)
List of species records to be evaluated filtered by logged in user (Table of records to be evaluated, with accepted, rejected, pending radio-button designations. Once accepted or rejected, a record should drop off the list on a refresh). Default value should be pending.

**Comment by timlinux** [comment]
Is this an evaluation of the collection / occurrence record or the taxonomic status?

**Comment by gubuntu** [comment]
merged with #24
