### ISSUE TITLE
Re-Skin LEDET-BIMS

### ISSUE THREAD

**Issue by cchristelis** [kartoza/LEDET_BIMS#91]
# Problem

The design needed to conform to the LEDET corporate identity. @carina1000 updated the mockups acordingly. These can be viewed here: https://app.moqups.com/tim@kartoza.com/47tU30vEA3/edit/page/a407f8694

# Proposed Solution

Update the CSS and HTML according to the mockups.

**Comment by gubuntu** [comment]
Sorry guys but this needs to be like the original floating menu mockup, not the bar across the top like Healthyrivers.

**Comment by carina1000** [comment]
Hi @gubuntu I thought in our last chat we decided to change it?

**Comment by gubuntu** [comment]
Nope I said they want to keep it as per the original design. The bar takes up map real estate for one and on some screens menu items are duplicated. 

It will also be a good test of inheriting css from django-bims and applying different local changes in LEDET and healthyrivers.

**Comment by gubuntu** [comment]
@dimasciput I think this is done, please close if you agree
