### ISSUE TITLE
FR18 summary statistic visualisation

### ISSUE THREAD

**Issue by sonlinux** [kartoza/LEDET_BIMS#97]
If a user selects one or more features in a layer, 
> The LBIMS shall present summary statistics of selected data on the UI in an  visualisation format (graphical, tabular etc.) appropriate the type of statistic.

Exactly what need to be dsplayed about which layers and how exactly it should be displayed must be specified by LEDET in the form of a template or example before implementation.

**Comment by gubuntu** [comment]
In the present implementation, this is what will appear in the popup and in the right sidebar when selecting a number of features in an active layer @cchristelis ?

**Comment by cchristelis** [comment]
@carina1000 please hand this back to @sonlinux, when you have a mockup or concept back.

**Comment by gubuntu** [comment]
should come through from healthyrivers

**Comment by dimasciput** [comment]
site and taxon detail just like in healthyrivers
